// <auto-generated> RADIATA OWNER PICKS — do not hand-edit. Regenerate with
// `Radiata.exe --export-mypicks --only="Overwatch;Despelote"`, then copy %APPDATA%\Radiata\CuratedArtOwner.g.cs over this file.
// That run re-resolved only the scoped games; rows marked (carried) came through from the
// table the running build shipped, so re-running it needs that same build, not a clean one.
// Data: the author's own Game Grid art choices, pinned as explicit SteamGridDB URLs —
// additions to the Picker's Top-100 table in CuratedArt.g.cs. See OwnerPicksExport.cs. </auto-generated>
namespace ControllerWheel;

internal static partial class CuratedArt
{
    /// <summary>Consulted only when <c>Table</c> has no entry — see <see cref="Get"/>.</summary>
    private static readonly Dictionary<string, Entry> OwnerTable = new(StringComparer.Ordinal)
    {
        // Bejeweled 3  [EA]  (carried from an earlier bake)
        ["bejeweled3"] = new("https://cdn2.steamgriddb.com/grid/40c2026e6f4de244e16cd0d70aca29c3.png", null, null, false, null),
        // Bendy and the Ink Machine  [Steam]  (carried from an earlier bake)
        ["bendyandtheinkmachine"] = new("https://cdn2.steamgriddb.com/grid/a4a39e8d061601e46f61ddc777113e8c.png", null, "https://cdn2.steamgriddb.com/logo/54072f485cdb7897ebbcaf7525139561.png", false, null),
        // Blue Prince  [Steam]  (carried from an earlier bake)
        ["blueprince"] = new("https://cdn2.steamgriddb.com/grid/325ab9f1731fdc4a2cffc4de6f5c480b.png", null, null, true, null),
        // Buckshot Roulette  [Steam]  (carried from an earlier bake)
        ["buckshotroulette"] = new("https://cdn2.steamgriddb.com/grid/ec9108ae750f87305c813725b5cf409a.png", null, "https://cdn2.steamgriddb.com/logo/1eb0bb2592024cedf6b2cc140114a785.png", false, null),
        // deeprockgalactic  [not installed]  (carried from an earlier bake)
        ["deeprockgalactic"] = new("https://cdn2.steamgriddb.com/grid/9c8d8b6698dd0dc195d35179f7e27543.png", null, null, false, null),
        // despelote  [Steam]  (cover: default, logo: hidden)
        ["despelote"] = new(null, null, null, true, null),
        // DREDGE  [GOG]  (carried from an earlier bake)
        ["dredge"] = new("https://cdn2.steamgriddb.com/grid/316d84fc4c76568ae8b12ed18bae7afb.png", null, "https://cdn2.steamgriddb.com/logo/2954d410635705bc7252570988ea62e3.png", false, null),
        // ENSLAVED™: Odyssey to the West™ Premium Edition  [Steam]  (carried from an earlier bake)
        ["enslavedodysseytothewestpremiumedition"] = new("https://cdn2.steamgriddb.com/grid/f08a8b395b122e0bb95ca2fe5002c889.png", null, "https://cdn2.steamgriddb.com/logo/2c716988ac1b99bd54ad746dd51d3c55.png", false, null),
        // Firewatch  [Steam]  (carried from an earlier bake)
        ["firewatch"] = new("https://cdn2.steamgriddb.com/grid/617025a2c76698e17a0e34e58642e104.png", null, null, false, null),
        // Frog Fractions: Game of the Decade Edition  [Steam]  (carried from an earlier bake)
        ["frogfractionsgameofthedecadeedition"] = new(null, "15331E", "https://cdn2.steamgriddb.com/logo/0ebacf43a429d8992a0ff3f0d0762189.png", false, null),
        // Gang Beasts  [Xbox]  (carried from an earlier bake)
        ["gangbeasts"] = new("https://cdn2.steamgriddb.com/grid/3847643ff52cb99dd30ed49dec3b533f.png", null, "https://cdn2.steamgriddb.com/logo/986648642d1a68a3178f6869689cc260.png", false, null),
        // Glittermitten Grove  [Steam]  (carried from an earlier bake)
        ["glittermittengrove"] = new("https://cdn2.steamgriddb.com/grid/6558a36e80b682c4dfd415cacfd2c17d.png", null, null, false, null),
        // HELLDIVERS™  [Steam]  (carried from an earlier bake)
        ["helldivers"] = new("https://cdn2.steamgriddb.com/grid/287ba93e55a8303f1475f8f17807c938.png", null, null, false, null),
        // Herdling  [Steam]  (carried from an earlier bake)
        ["herdling"] = new("https://cdn2.steamgriddb.com/grid/f97398c9ed20df21b6a1bd97c372f40d.png", null, null, false, null),
        // Her Story  [Steam]  (carried from an earlier bake)
        ["herstory"] = new("https://cdn2.steamgriddb.com/grid/3c98974ceccf226f4a6099cee324a957.png", null, null, false, null),
        // How Fish Is Made  [Steam]  (carried from an earlier bake)
        ["howfishismade"] = new("https://cdn2.steamgriddb.com/grid/b5f7501759294847cc34c6c8114cc107.png", null, null, false, null),
        // Into the Breach  [Steam]  (carried from an earlier bake)
        ["intothebreach"] = new("https://cdn2.steamgriddb.com/grid/e560c0f08fd9275c510d990e00add84d.png", null, null, false, null),
        // Keeper  [Steam]  (carried from an earlier bake)
        ["keeper"] = new("https://cdn2.steamgriddb.com/grid/5fa1279c2b3d293ea80964b32ce248c0.png", null, "https://cdn2.steamgriddb.com/logo/2295e0bcab507f1743f649a86280faaa.png", false, null),
        // KIDS  [itch.io]  (carried from an earlier bake)
        ["kids"] = new("https://cdn2.steamgriddb.com/grid/fdc210e25c7a92f3f1df16696893896a.png", null, null, true, null),
        // Later Alligator  [Steam]  (carried from an earlier bake)
        ["lateralligator"] = new("https://cdn2.steamgriddb.com/grid/ecec67534f2300915a5b8452b14fc3d1.jpg", null, "https://cdn2.steamgriddb.com/logo/728fe26e7649c1d38f65967f6c05115b.png", false, null),
        // Lugaru HD   [Steam]  (carried from an earlier bake)
        ["lugaruhd"] = new("https://cdn2.steamgriddb.com/grid/1a01f836b0c2494b9e95700f520f7df4.png", null, null, false, null),
        // MECCHA CHAMELEON  [Steam]  (carried from an earlier bake)
        ["mecchachameleon"] = new("https://cdn2.steamgriddb.com/grid/fedb1d5db502d63e6a8cce851ed0c90c.png", null, "https://cdn2.steamgriddb.com/logo/ffd103eda3cf1ed6629aaac39071321b.png", false, null),
        // Nidhogg  [Steam]  (carried from an earlier bake)
        ["nidhogg"] = new("https://cdn2.steamgriddb.com/grid/b8edb728af299add1c082315f574db86.png", null, null, false, null),
        // Overwatch®  [Steam]  (cover: pick, logo: hidden)
        ["overwatch"] = new("https://cdn2.steamgriddb.com/grid/50a48887dbac4af731ea8abd7c19ebe5.png", null, null, true, null),
        // Papers, Please  [Steam]  (carried from an earlier bake)
        ["papersplease"] = new(null, "15243F", null, true, null),
        // PEAK  [Steam]  (carried from an earlier bake)
        ["peak"] = new("https://cdn2.steamgriddb.com/grid/e1ff57a62292d5946c3d94dd25adab53.png", null, "https://cdn2.steamgriddb.com/logo/4e3d6212dd67def76238cdbf47055e6a.png", false, null),
        // PlayStation®VR2 App  [Steam]  (carried from an earlier bake)
        ["playstationvr2app"] = new("https://cdn2.steamgriddb.com/grid/a41f331ffa41bebfbb5f1a2fb2c24574.png", null, null, false, null),
        // Portal 2  [Steam]  (carried from an earlier bake)
        ["portal2"] = new("https://cdn2.steamgriddb.com/grid/f27159c8f16ed644c45ba8598d7dd975.png", null, "https://cdn2.steamgriddb.com/logo/86561200f3f1f2bf5cd4218495323b3f.png", false, null),
        // Portal: Revolution  [Steam]  (carried from an earlier bake)
        ["portalrevolution"] = new("https://cdn2.steamgriddb.com/grid/347efc8e09fcfd7a8883edb436df5db1.png", null, "https://cdn2.steamgriddb.com/logo/71d08a4209dc71993e625796d6926882.png", false, null),
        // Prince of Persia  [Steam]  (carried from an earlier bake)
        ["princeofpersia"] = new("https://cdn2.steamgriddb.com/grid/003b36afc53d4e078a9df02e0e43fb28.png", null, null, false, null),
        // Quake II Enhanced  [GOG]  (carried from an earlier bake)
        ["quakeiienhanced"] = new(null, null, "https://cdn2.steamgriddb.com/logo/718572810891feeb6e075caf65eecfce.png", false, null),
        // R.E.P.O.  [Steam]  (carried from an earlier bake)
        ["repo"] = new("https://cdn2.steamgriddb.com/grid/f82466e533839f21d088f85ef6bb2802.jpg", null, "https://cdn2.steamgriddb.com/logo/a3f2ad23852a72af62ecb68eb765b281.png", false, null),
        // senuassagahellbladeii  [not installed]  (carried from an earlier bake)
        ["senuassagahellbladeii"] = new("https://cdn2.steamgriddb.com/grid/f42e9a824b3641379994c1445694ee1d.png", null, null, true, null),
        // Snufkin: Melody of Moominvalley  [Steam]  (carried from an earlier bake)
        ["snufkinmelodyofmoominvalley"] = new("https://cdn2.steamgriddb.com/grid/fc91e8e3ff44679fd70240aa6f7ad635.jpg", null, null, false, null),
        // StarCraft  [Battle.net]  (carried from an earlier bake)
        ["starcraft"] = new("https://cdn2.steamgriddb.com/grid/2483125d070c795ba1ed28b241c5c737.png", null, null, false, null),
        // SteamVR  [Steam]  (carried from an earlier bake)
        ["steamvr"] = new("https://cdn2.steamgriddb.com/grid/0abeae1d918c94a5699d208e525b1e0b.png", null, null, false, null),
        // Teenage Mutant Ninja Turtles: Shredder's Revenge  [Xbox]  (carried from an earlier bake)
        ["teenagemutantninjaturtlesshreddersrevenge"] = new("https://cdn2.steamgriddb.com/grid/94ec6bfb7fa1f2a3bd770dd17f9ee431.png", null, "https://cdn2.steamgriddb.com/logo/74315d8e1170ea8b75753a9bd0464be5.png", false, null),
        // The Binding of Isaac: Rebirth  [Steam]  (carried from an earlier bake)
        ["thebindingofisaacrebirth"] = new("https://cdn2.steamgriddb.com/grid/9225f94fcf3b4d44b0bf58a9eb71f289.png", null, null, false, null),
        // Time Flies  [Steam]  (carried from an earlier bake)
        ["timeflies"] = new(null, null, null, true, null),
        // UFO 50  [Steam]  (carried from an earlier bake)
        ["ufo50"] = new("https://cdn2.steamgriddb.com/grid/99457009a981c4ee7a69f924fcc4ea42.png", null, "https://cdn2.steamgriddb.com/logo/e97a66c8da9aeb9b6f20243b4f8a11ff.png", false, null),
        // West of Loathing  [Steam]  (carried from an earlier bake)
        ["westofloathing"] = new("https://cdn2.steamgriddb.com/grid/08f4adf6fa1aee5bd6e3eb8887f45297.png", null, "https://cdn2.steamgriddb.com/logo/92b40b8559fe179c5bb2c5220cc27334.png", false, null),
        // Year Walk  [Steam]  (carried from an earlier bake)
        ["yearwalk"] = new("https://cdn2.steamgriddb.com/grid/c68493da478cb992662feefd6ecf0b46.png", null, null, false, null),
    };
}
