using System.Text;
using System.Text.RegularExpressions;
using Radiata.ExtractStrings;

// Two jobs, both from the repo root:
//   dotnet run --project tools/ExtractStrings                       → rewrite Core/UiStrings.g.cs from every *.xaml
//   dotnet run --project tools/ExtractStrings -- --convert <file.xaml> [--dry]
//                                                                    → rewrite the mechanical literals in ONE file to
//                                                                      {loc:T …}, add xmlns:loc, print what it left alone
// Exit 0 = fine; 1 = a problem the runtime checker cannot see (an unquoted {loc:T …} carrying , = { or },
// or a value XML attribute normalization would have altered: a newline, a tab, a doubled space).
var root = FindRepoRoot();

if (args.Length >= 2 && args[0] == "--convert")
    return Convert(Path.IsPathRooted(args[1]) ? args[1] : Path.Combine(root, args[1]), dry: args.Contains("--dry"));

return Extract(root);

// ── Extraction ────────────────────────────────────────────────────────────────

static int Extract(string root)
{
    var found = new List<(string File, string Text)>();
    var problems = new List<string>();

    foreach (var path in XamlStrings.EnumerateFiles(root))
        foreach (var x in XamlStrings.Enumerate(path, problems))
            found.Add((x.File, x.Text));

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated> UI STRING CATALOG — do not hand-edit. Regenerate with");
    sb.AppendLine("// `dotnet run --project tools/ExtractStrings` from the repo root, which walks every *.xaml for");
    sb.AppendLine("// {loc:T …} and loc:LocRich.Source=\"…\" and rewrites this file. Committed on purpose (the public mirror");
    sb.AppendLine("// does not carry tools/). Consumed by Loc.SourceStrings() so --check-locales can report a XAML string");
    sb.AppendLine("// with no translation. </auto-generated>");
    sb.AppendLine("namespace ControllerWheel;");
    sb.AppendLine();
    sb.AppendLine("internal static partial class UiStrings");
    sb.AppendLine("{");
    sb.AppendLine("    /// <summary>Every English string authored in XAML, in file/attribute order.</summary>");
    sb.AppendLine("    public static readonly string[] All =");
    sb.AppendLine("    [");
    string? lastFile = null;
    var distinct = found.DistinctBy(f => f.Text).ToList();
    foreach (var (file, s) in distinct)
    {
        if (file != lastFile) { sb.AppendLine($"        // ── {file} ──"); lastFile = file; }
        sb.AppendLine($"        {Lit(s)},");
    }
    sb.AppendLine("    ];");
    sb.AppendLine("}");

    var outPath = Path.Combine(root, "Core", "UiStrings.g.cs");
    var output = sb.ToString();
    bool changed = !File.Exists(outPath) || File.ReadAllText(outPath) != output;
    if (changed) File.WriteAllText(outPath, output, new UTF8Encoding(false));
    Console.WriteLine($"{found.Count} XAML strings ({distinct.Count} distinct) → Core/UiStrings.g.cs{(changed ? " (rewritten)" : " (unchanged)")}");
    foreach (var p in problems) Console.Error.WriteLine("PROBLEM  " + p);
    return problems.Count == 0 ? 0 : 1;
}

// ── Conversion ────────────────────────────────────────────────────────────────
// Line-based on purpose: XDocument.Save would reflow every element onto one line and destroy the hand
// formatting. Only the mechanical cases convert; everything else is listed for a human:
//   • Text= converts on a <TextBlock> (same line, or a continuation line of a still-open <TextBlock …> tag),
//     never on a TextBox, where Text is a VALUE the user edits.
//   • A line holding exactly ONE translatable <Run> is a label (section heading beside a help chip) and its
//     Text converts; a line with several is a sentence built from fragments and is left for LocRich.Source.
//   • A value with , ' or = takes the quoted form {loc:T '…'} with ' escaped as \'; braces are left alone.

static int Convert(string path, bool dry)
{
    var lines = File.ReadAllLines(path).ToList();
    var name = Path.GetFileName(path);
    int converted = 0;
    var leftovers = new List<string>();

    var attr   = new Regex("(?<pre>\\s)(?<name>Text|Content|Header|ToolTip|AutomationProperties\\.Name)=\"(?<val>[^\"{}]+)\"");
    var openTg = new Regex("<(?<tag>[A-Za-z][A-Za-z0-9.]*)");
    var runTxt = new Regex("<Run\\s[^>]*?Text=\"(?<val>[^\"{}]+)\"");
    string? openTag = null;   // the element whose start tag is still open at the end of the previous line

    for (int i = 0; i < lines.Count; i++)
    {
        var line = lines[i];
        bool comment = line.TrimStart().StartsWith("<!--", StringComparison.Ordinal);

        // Which element is this line's Text= for? A tag opened on this line, else the tag left open above.
        var tagsHere = openTg.Matches(line).Select(m => m.Groups["tag"].Value).ToList();
        string? lineTag = tagsHere.Count > 0 ? tagsHere[^1] : openTag;

        if (!comment)
        {
            // Single-label <Run>: exactly one translatable Run on the line, no other prose Run beside it.
            var runs = runTxt.Matches(line).Where(m => Translatable(m.Groups["val"].Value)).ToList();
            if (runs.Count == 1 && !line.Contains("<Hyperlink", StringComparison.Ordinal))
            {
                var m = runs[0]; string v = m.Groups["val"].Value;
                if (v.IndexOfAny(['{', '}']) < 0)
                {
                    string q = XamlStrings.Quote(v);
                    line = line[..m.Groups["val"].Index] + q + line[(m.Groups["val"].Index + v.Length)..];
                    converted++;
                }
                else Leftover(i, "<Run> label with braces", v);
            }
            else if (runs.Count == 1)   // a lone label beside a <Hyperlink>: convert the Run by hand (its Text is a DP)
                Leftover(i, "<Run> beside a <Hyperlink> — convert its Text by hand", runs[0].Groups["val"].Value);
            else if (runs.Count > 1)
                foreach (var m in runs) Leftover(i, "<Run> fragment — rebuild the sentence as LocRich.Source", m.Groups["val"].Value);

            line = attr.Replace(line, m =>
            {
                string n = m.Groups["name"].Value, v = m.Groups["val"].Value;
                if (line.Substring(0, m.Index).Contains("<Run", StringComparison.Ordinal) && n == "Text" && runTxt.IsMatch(line)) return m.Value;   // handled above
                if (!Translatable(v)) return m.Value;
                if (n == "Text" && lineTag != "TextBlock") { Leftover(i, $"Text= on <{lineTag ?? "?"}> (a value, not a label?)", v); return m.Value; }
                if (v.IndexOfAny(['{', '}']) >= 0) { Leftover(i, "braces — use LocRich.Source", v); return m.Value; }
                converted++;
                return $"{m.Groups["pre"].Value}{n}=\"{XamlStrings.Quote(v)}\"";
            });
            lines[i] = line;
        }

        // Track the open start tag across lines: a tag opened here and not closed on this line stays open;
        // any '>' after the last '<' closes whatever was open.
        int lastLt = line.LastIndexOf('<'), lastGt = line.LastIndexOf('>');
        if (tagsHere.Count > 0) openTag = lastGt > lastLt ? null : tagsHere[^1];
        else if (lastGt >= 0) openTag = null;
    }

    if (converted > 0 && !lines.Any(l => l.Contains("xmlns:loc=\"clr-namespace:ControllerWheel\"", StringComparison.Ordinal)))
    {
        int x = lines.FindIndex(l => l.Contains("xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"", StringComparison.Ordinal));
        if (x < 0) { Console.Error.WriteLine("PROBLEM  no xmlns:x line to anchor xmlns:loc on"); return 1; }
        string indent = new string(' ', lines[x].TakeWhile(c => c == ' ').Count());
        bool closesRoot = lines[x].TrimEnd().EndsWith(">", StringComparison.Ordinal);
        if (closesRoot)
        {
            lines[x] = lines[x].TrimEnd().TrimEnd('>');
            lines.Insert(x + 1, indent + "xmlns:loc=\"clr-namespace:ControllerWheel\">");
        }
        else lines.Insert(x + 1, indent + "xmlns:loc=\"clr-namespace:ControllerWheel\"");
    }

    void Leftover(int i, string why, string v) => leftovers.Add($"{name}:{i + 1}: {why}: {XamlStrings.Excerpt(v)}");

    if (!dry) File.WriteAllLines(path, lines, new UTF8Encoding(false));
    Console.WriteLine($"{name}: {converted} literals → {{loc:T …}}{(dry ? " (dry run, nothing written)" : "")}, {leftovers.Count} left for a human");
    foreach (var l in leftovers.Distinct()) Console.WriteLine("  " + l);
    return 0;
}

/// Skip what a translator never touches: no letters (glyphs, numbers, "…", "?"), XML character entities used as
/// icon glyphs, URLs, the product name, and a copyright line.
static bool Translatable(string v)
{
    if (!v.Any(char.IsLetter)) return false;
    if (v.StartsWith("&#", StringComparison.Ordinal)) return false;
    if (v.StartsWith("http", StringComparison.OrdinalIgnoreCase)) return false;
    if (v is "Radiata" || v.StartsWith("©", StringComparison.Ordinal)) return false;
    return true;
}

static string Lit(string s) =>
    "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t") + "\"";

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "ControllerWheel.csproj"))) dir = dir.Parent;
    return dir?.FullName ?? throw new InvalidOperationException("run from inside the repo (ControllerWheel.csproj not found upward)");
}
