namespace ControllerWheel;

/// <summary>
/// GENERATED from docs/PC_GAME_TEXT_CHAT_BUTTONS.md — edit that table and re-run the conversion, never
/// this map by hand.
///
/// Maps a PC game's display name to the single key it uses to open its in-game TEXT chat box (used by
/// the "text-chat" slice action in "Try Game Default" mode — see Core/ActionExecutor.cs). Every value
/// must stay a token <see cref="ControllerWheel.KeypressSender"/> can parse ("Enter", "T", "Y", the
/// literal '/' used by Roblox and DayZ (maps to VK_OEM_2), '`' (VK_OEM_3), and "Mod+Key" chords like
/// "Ctrl+T" which <see cref="KeypressSender.TrySend"/> also parses).
///
/// Every entry below is individually source-verified (official docs, PCGamingWiki, wikis, press/community
/// guides) — see the source doc's "Verified" tables for citations. 500 games verified total. 250 more were
/// excluded as scope errors (no text chat / not a PC game / duplicate / cancelled or shut-down / click-only
/// chat UI / unsendable input pattern — doc's "Excluded" tables, generating <see cref="NoTextChat"/>) and 56
/// remain unresolved (doc's "Needs re-verification" table) — those 56 aren't in either <see cref="Map"/>
/// or <see cref="NoTextChat"/>, so RunTextChat refuses to fire for them too: an unconfirmed key isn't
/// guessed as Enter, same as any other installed game not in this table.
/// </summary>
public static class GameChatButtons
{
    // Verbatim from the source table's "Verified" section (Name → Chat Button); game names are unique in it.
    private static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Counter-Strike 2"] = "Y",
        ["Dota 2"] = "Enter",
        ["League of Legends"] = "Enter",
        ["VALORANT"] = "Enter",
        ["Overwatch 2"] = "Enter",
        ["Rocket League"] = "T",
        ["Fortnite"] = "Enter",
        ["Apex Legends"] = "Enter",
        ["Tom Clancy's Rainbow Six Siege"] = "T",
        ["Call of Duty: Warzone"] = "Enter",
        ["Call of Duty: Black Ops 6"] = "Enter",
        ["Call of Duty: Modern Warfare III"] = "Enter",
        ["Destiny 2"] = "Enter",
        ["Warframe"] = "T",
        ["Grand Theft Auto V"] = "T",
        ["Minecraft: Java Edition"] = "T",
        ["Minecraft: Bedrock Edition"] = "T",
        ["Roblox"] = "/",
        ["Marvel Rivals"] = "Enter",
        ["Helldivers 2"] = "Enter",
        ["Palworld"] = "Enter",
        ["ARK: Survival Evolved"] = "Enter",
        ["ARK: Survival Ascended"] = "Enter",
        ["Rust"] = "T",
        ["DayZ"] = "/",
        ["Sea of Thieves"] = "T",
        ["Lethal Company"] = "/",
        ["Among Us"] = "Enter",
        ["VRChat"] = "Y",
        ["Garry's Mod"] = "Y",
        ["Team Fortress 2"] = "Y",
        ["Left 4 Dead 2"] = "Y",
        ["Left 4 Dead"] = "Y",
        ["PAYDAY 2"] = "T",
        ["PAYDAY 3"] = "Enter",
        ["Deep Rock Galactic"] = "Enter",
        ["Killing Floor 2"] = "T",
        ["Squad"] = "J",
        ["Squad 44"] = "J",
        ["Hell Let Loose"] = "K",
        ["Arma 3"] = "/",
        ["Arma Reforger"] = "Enter",
        ["Battlefield 2042"] = "Enter",
        ["Battlefield V"] = "Enter",
        ["Battlefield 1"] = "J",
        ["Battlefield 4"] = "J",
        ["BattleBit Remastered"] = "Y",
        ["World of Tanks"] = "Enter",
        ["World of Warships"] = "Enter",
        ["War Thunder"] = "Enter",
        ["Enlisted"] = "Enter",
        ["MechWarrior Online"] = "T",
        ["World of Warcraft"] = "Enter",
        ["Final Fantasy XIV Online"] = "Enter",
        ["The Elder Scrolls Online"] = "Enter",
        ["Star Wars: The Old Republic"] = "Enter",
        ["RuneScape"] = "Enter",
        ["Old School RuneScape"] = "Enter",
        ["Black Desert"] = "Enter",
        ["Lost Ark"] = "Enter",
        ["Throne and Liberty"] = "Enter",
        ["New World: Aeternum"] = "Enter",
        ["Albion Online"] = "Enter",
        ["EVE Online"] = "Space",
        ["Path of Exile"] = "Enter",
        ["Path of Exile 2"] = "Enter",
        ["Diablo IV"] = "Enter",
        ["Diablo III"] = "Enter",
        ["Last Epoch"] = "Enter",
        ["MapleStory"] = "Enter",
        ["Mabinogi"] = "Enter",
        ["TERA"] = "Enter",
        ["Aion"] = "Enter",
        ["Blade & Soul"] = "Enter",
        ["Neverwinter"] = "Enter",
        ["Star Trek Online"] = "Enter",
        ["DC Universe Online"] = "Enter",
        ["Dungeons & Dragons Online"] = "Enter",
        ["RIFT"] = "Enter",
        ["Trove"] = "Enter",
        ["Palia"] = "Enter",
        ["Once Human"] = "Enter",
        ["Conan Exiles"] = "Enter",
        ["V Rising"] = "Enter",
        ["Valheim"] = "Enter",
        ["No Man's Sky"] = "Enter",
        ["Grounded"] = "Enter",
        ["Sons of the Forest"] = "Enter",
        ["The Forest"] = "Enter",
        ["Don't Starve Together"] = "Y",
        ["7 Days to Die"] = "T",
        ["SCUM"] = "T",
        ["Icarus"] = "Enter",
        ["Myth of Empires"] = "Ctrl+T",
        ["Soulmask"] = "Enter",
        ["Core Keeper"] = "Enter",
        ["Terraria"] = "Enter",
        ["Starbound"] = "Enter",
        ["Satisfactory"] = "Enter",
        ["Factorio"] = "`",
        ["Space Engineers"] = "Enter",
        ["Empyrion - Galactic Survival"] = "Enter",
        ["Unturned"] = "Enter",
        ["Creativerse"] = "Enter",
        ["Eco"] = "C",
        ["Vintage Story"] = "T",
        ["Stalcraft: X"] = "Enter",
        ["Delta Force"] = "Enter",
        ["Splitgate 2"] = "Enter",
        ["Splitgate"] = "Enter",
        ["Halo Infinite"] = "Y",
        ["Quake Champions"] = "T",
        ["Rogue Company"] = "Enter",
        ["SMITE"] = "Enter",
        ["SMITE 2"] = "Enter",
        ["Paladins"] = "Enter",
        ["Predecessor"] = "Enter",
        ["Brawlhalla"] = "Enter",
        ["For Honor"] = "T",
        ["Chivalry 2"] = "T",
        ["Mordhau"] = "Y",
        ["Mount & Blade II: Bannerlord"] = "Enter",
        ["Age of Empires II: Definitive Edition"] = "Enter",
        ["Age of Empires IV"] = "Enter",
        ["StarCraft II"] = "Enter",
        ["Warcraft III: Reforged"] = "Enter",
        ["Company of Heroes 2"] = "Enter",
        ["Stellaris"] = "Enter",
        ["iRacing"] = "T",
        ["Assetto Corsa Competizione"] = "Enter",
        ["Assetto Corsa"] = "Enter",
        ["Trackmania"] = "Enter",
        ["Wreckfest"] = "Enter",
        ["Magic: The Gathering Online"] = "Enter",
        ["Teamfight Tactics"] = "Enter",
        ["Arena Breakout: Infinite"] = "Enter",
        ["Gray Zone Warfare"] = "Z",
        ["The Cycle: Frontier"] = "Enter",
        ["Super People 2"] = "T",
        ["Planetside 2"] = "Enter",
        ["Black Squad"] = "Enter",
        ["Ironsight"] = "Enter",
        ["Fistful of Frags"] = "Y",
        ["Day of Defeat: Source"] = "Y",
        ["Counter-Strike: Source"] = "Y",
        ["Counter-Strike 1.6"] = "Y",
        ["Half-Life 2: Deathmatch"] = "Y",
        ["Sven Co-op"] = "Y",
        ["Alien Swarm: Reactive Drop"] = "Y",
        ["Warface: Clutch"] = "Y",
        ["Wolfenstein: Enemy Territory"] = "T",
        ["Urban Terror"] = "Y",
        ["Xonotic"] = "T",
        ["OpenArena"] = "T",
        ["Quake Live"] = "T",
        ["Foxhole"] = "Enter",
        ["OpenRA"] = "Enter",
        ["Mindustry"] = "Enter",
        ["OpenTTD"] = "Enter",
        ["DCS World"] = "Shift+Tab",
        ["IL-2 Sturmovik: Great Battles"] = "Enter",
        ["Elite Dangerous"] = "C",
        ["World of Warcraft Classic"] = "Enter",
        ["World of Warcraft: The War Within"] = "Enter",
        ["Elsword"] = "Enter",
        ["Grand Chase Classic"] = "Enter",
        ["Closers"] = "Enter",
        ["The First Descendant"] = "Enter",
        ["Blue Protocol: Star Resonance"] = "Enter",
        ["Tower of Fantasy"] = "Enter",
        ["Genshin Impact"] = "Enter",
        ["Wuthering Waves"] = "Enter",
        ["Where Winds Meet"] = "Enter",
        ["War Robots"] = "Enter",
        ["Mechabellum"] = "Enter",
        ["World of Tanks Blitz"] = "Enter",
        ["World of Warplanes"] = "Enter",
        ["Roblox: Adopt Me!"] = "/",
        ["Roblox: Brookhaven RP"] = "/",
        ["Roblox: Blox Fruits"] = "/",
        ["Roblox: Murder Mystery 2"] = "/",
        ["Roblox: Dress to Impress"] = "/",
        ["Roblox: Blade Ball"] = "/",
        ["Roblox: Arsenal"] = "/",
        ["Roblox: BedWars"] = "/",
        ["Roblox: Pet Simulator 99"] = "/",
        ["Roblox: The Strongest Battlegrounds"] = "/",
        ["Rec Room"] = "Y",
        ["Second Life"] = "Enter",
        ["IMVU"] = "Enter",
        ["Habbo"] = "Enter",
        ["Tower Unite"] = "Y",
        ["Pummel Party"] = "T",
        ["Crab Game"] = "Enter",
        ["R.E.P.O."] = "T",
        ["Human: Fall Flat"] = "T",
        ["Stick Fight: The Game"] = "Enter",
        ["Ultimate Chicken Horse"] = "T",
        ["Duck Game"] = "Enter",
        ["SpeedRunners"] = "Enter",
        ["Monster Hunter Wilds"] = "Insert",
        ["Monster Hunter: World"] = "Insert",
        ["Monster Hunter Rise"] = "Enter",
        ["Dauntless"] = "Enter",
        ["Borderlands 3"] = "Y",
        ["Borderlands 2"] = "Y",
        ["Tiny Tina's Wonderlands"] = "Enter",
        ["Back 4 Blood"] = "Y",
        ["Dying Light 2 Stay Human"] = "Enter",
        ["Dying Light"] = "Enter",
        ["Dead Island 2"] = "U",
        ["Dead Island Definitive Edition"] = "Enter",
        ["GTA Online"] = "T",
        ["FiveM"] = "T",
        ["RAGE Multiplayer"] = "T",
        ["SAMP"] = "T",
        ["Euro Truck Simulator 2"] = "Y",
        ["American Truck Simulator"] = "Y",
        ["Farming Simulator 25"] = "T",
        ["The Crew 2"] = "F3",
        ["The Elder Scrolls Online: Gold Road"] = "Enter",
        ["Guild Wars 2: Janthir Wilds"] = "Enter",
        ["Final Fantasy XI"] = "Space",
        ["EverQuest"] = "Enter",
        ["EverQuest II"] = "Enter",
        ["Lord of the Rings: Return to Moria"] = "Enter",
        ["Dune: Awakening"] = "Enter",
        ["Pax Dei"] = "Enter",
        ["Nightingale"] = "Enter",
        ["Smalland: Survive the Wilds"] = "T",
        ["Deadside"] = "F6",
        ["Supervive"] = "Enter",
        ["FragPunk"] = "Enter",
        ["Shatterline"] = "Y",
        ["Blood Strike"] = "Enter",

        ["Battlefield 3"] = "J",
        ["Company of Heroes 3"] = "Enter",
        ["Europa Universalis IV"] = "Tab",
        ["Men of War II"] = "Enter",
        ["Men of War: Assault Squad 2"] = "Enter",
        ["Wargame: Red Dragon"] = "Enter",
        ["WARNO"] = "Enter",
        ["Steel Division 2"] = "Enter",
        ["Regiments"] = "Enter",
        ["Battle for Middle-earth II"] = "Enter",
        ["Command & Conquer Remastered Collection"] = "Enter",
        ["Command & Conquer 3: Tiberium Wars"] = "Enter",
        ["Red Alert 3"] = "Enter",
        ["Stronghold Crusader HD"] = "Enter",
        ["Tropico 6"] = "Enter",
        ["Age of Empires III: Definitive Edition"] = "Enter",
        ["Age of Mythology: Retold"] = "Enter",
        ["MU Online"] = "Enter",
        ["MU Legend"] = "Enter",
        ["Cabal Online"] = "Enter",
        ["Silkroad Online"] = "Enter",
        ["Ragnarok Online"] = "Enter",
        ["Tree of Savior"] = "Enter",
        ["La Tale"] = "Enter",
        ["Dungeon Fighter Online"] = "Enter",
        ["Vindictus"] = "Enter",
        ["Champions Online"] = "Enter",
        ["Insurgency: Sandstorm"] = "Y",
        ["Unreal Tournament 2004"] = "T",
        ["Unreal Tournament 3"] = "T",
        ["America's Army: Proving Grounds"] = "T",
        ["America's Army 3"] = "T",
        ["Rising Storm 2: Vietnam"] = "Y",
        ["Red Orchestra 2"] = "Y",
        ["Verdun"] = "Y",
        ["Tannenberg"] = "Y",
        ["Isonzo"] = "Y",
        ["Team Fortress Classic"] = "Y",
        ["PUBG: BATTLEGROUNDS"] = "T",
        ["Party Animals"] = "Enter",
        ["Hunt: Showdown 1896"] = "Enter",
        ["Crossout"] = "Enter",
        ["Project Zomboid"] = "T",
        ["Enshrouded"] = "O",
        ["Halo: The Master Chief Collection"] = "J",
        ["Deadlock"] = "Enter",
        ["Stormgate"] = "Enter",
        ["Northgard"] = "Enter",
        ["Beyond All Reason"] = "Enter",
        ["Zero-K"] = "Enter",
        ["Supreme Commander: Forged Alliance"] = "Enter",
        ["Total War: THREE KINGDOMS"] = "Y",
        ["Civilization V"] = "Tab",
        ["Humankind"] = "Enter",
        ["Guild Wars 2"] = "Enter",
        ["The Lord of the Rings Online"] = "Enter",
        ["CarX Drift Racing Online"] = "T",
        ["Forza Motorsport"] = "N",
        ["Pro Soccer Online"] = "Enter",
        ["Golf With Your Friends"] = "T",
        ["The Hunter: Call of the Wild"] = "T",
        ["Fishing Planet"] = "Tab",
        ["Russian Fishing 4"] = "Q",
        ["Tabletop Simulator"] = "Enter",
        ["Z1 Battle Royale"] = "Enter",
        ["Star Citizen"] = "F12",
        ["RuneScape: Dragonwilds"] = "Enter",
        ["Farming Simulator 22"] = "T",
        ["Riders of Icarus"] = "Enter",
        ["Astellia"] = "Enter",
        ["Phantasy Star Online 2 New Genesis"] = "Enter",
        ["Phantasy Star Online 2"] = "Enter",
        ["Warhammer 40,000: Darktide"] = "Enter",
        ["Warhammer: Vermintide 2"] = "Enter",
        ["Space Marine 2"] = "O",
        ["Earth Defense Force 6"] = "T",
        ["Earth Defense Force 5"] = "T",
        ["GTFO"] = "Enter",
        ["Barotrauma"] = "T",
        ["We Need To Go Deeper"] = "Enter",
        ["Void Crew"] = "Enter",
        ["Fae Farm"] = "T",
        ["Dinkum"] = "Enter",
        ["Stardew Valley"] = "T",
        ["LEGO Fortnite"] = "Enter",
        ["Fortnite Festival"] = "Enter",
        ["Rocket Racing"] = "Enter",
        ["Trackmania Turbo"] = "T",
        ["RaceRoom Racing Experience"] = "C",

        ["A Tale in the Desert"] = "Enter",
        ["Abiotic Factor"] = "Enter",
        ["AdventureQuest 3D"] = "Enter",
        ["Age of Empires: Definitive Edition"] = "Enter",
        ["Ale & Tale Tavern"] = "Enter",
        ["Anarchy Online"] = "Enter",
        ["APB Reloaded"] = "Home",
        ["Battlefield 6"] = "Enter",
        ["Beasts of Bermuda"] = "Enter",
        ["Beyond the Wire"] = "J",
        ["Boundless"] = "Enter",
        ["Brick Rigs"] = "Enter",
        ["Call of Duty: Black Ops 3"] = "T",
        ["Call of Duty: Black Ops 7"] = "Enter",
        ["Call of Duty: Black Ops Cold War"] = "Enter",
        ["Call of Duty: Modern Warfare (2019)"] = "Enter",
        ["Call of Duty: Modern Warfare 2 (2009)"] = "T",
        ["Call of Duty: Modern Warfare II (2022)"] = "Enter",
        ["Call of Duty: WWII"] = "T",
        ["Champions of Regnum"] = "Enter",
        ["Chivalry: Medieval Warfare"] = "Y",
        ["City of Heroes (Homecoming)"] = "Enter",
        ["Command & Conquer: Generals - Zero Hour"] = "Enter",
        ["Command & Conquer: Red Alert 2"] = "Enter",
        ["Conquer Online"] = "Enter",
        ["Craftopia"] = "Enter",
        ["Cuisine Royale"] = "Enter",
        ["Digimon Masters Online"] = "Enter",
        ["Dragon Ball Xenoverse 2"] = "Del",
        ["Dragon Nest"] = "Enter",
        ["Dungeon Defenders II"] = "Enter",
        ["Dungeons 3"] = "Enter",
        ["Earth Defense Force 4.1: Winter of Wonder"] = "T",
        ["Embers Adrift"] = "Enter",
        ["Endless Legend"] = "Enter",
        ["Endless Space 2"] = "Enter",
        ["Entropia Universe"] = "Enter",
        ["Escape Simulator"] = "Enter",
        ["Grand Fantasia"] = "Enter",
        ["Green Hell"] = "Enter",
        ["Ground Branch"] = "T",
        ["Farm Together"] = "T",
        ["Farm Together 2"] = "Y",
        ["Fiesta Online"] = "Enter",
        ["Flyff Universe"] = "Enter",
        ["Grounded 2"] = "Enter",
        ["Growtopia"] = "Enter",
        ["Guild Wars"] = "Enter",
        ["Half-Life: Deathmatch"] = "Y",
        ["Knight Online"] = "Enter",
        ["Krunker"] = "Enter",
        ["Last Oasis"] = "Enter",
        ["Legends of Aria"] = "Enter",
        ["Legion TD 2"] = "Enter",
        ["Lineage II"] = "Enter",
        ["Live for Speed"] = "T",
        ["Medieval Dynasty"] = "Y",
        ["Metin2"] = "Enter",
        ["Mortal Online 2"] = "Enter",
        ["Mount & Blade: Warband"] = "Y",
        ["Muck"] = "Enter",
        ["Necesse"] = "Enter",
        ["Novus Inceptio"] = "Enter",
        ["Offworld Trading Company"] = "Enter",
        ["Osiris: New Dawn"] = "Enter",
        ["Pantheon: Rise of the Fallen"] = "Enter",
        ["Path of Titans"] = "Enter",
        ["PAYDAY: The Heist"] = "T",
        ["Perfect World International"] = "Enter",
        ["Pixel Worlds"] = "Enter",
        ["Planetary Annihilation: TITANS"] = "Enter",
        ["Pool Nation FX"] = "T",
        ["Portal Knights"] = "T",
        ["Primal Carnage: Extinction"] = "T",
        ["Priston Tale"] = "Enter",
        ["Project CARS"] = "T",
        ["Project Winter"] = "Enter",
        ["Quake II"] = "T",
        ["Quake III Arena"] = "T",
        ["QuakeWorld"] = "T",
        ["RACE 07: Official WTCC Game"] = "C",
        ["Raft"] = "Enter",
        ["Ran Online"] = "Enter",
        ["Realm of the Mad God: Exalt"] = "Enter",
        ["Renegade X"] = "T",
        ["Return to Castle Wolfenstein"] = "T",
        ["rFactor"] = "T",
        ["Rise of Nations: Extended Edition"] = "Enter",
        ["Roblox: 99 Nights in the Forest"] = "/",
        ["Roblox: All Star Tower Defense"] = "/",
        ["Roblox: Anime Adventures"] = "/",
        ["Roblox: Anime Fighters Simulator"] = "/",
        ["Roblox: Bee Swarm Simulator"] = "/",
        ["Roblox: Berry Avenue"] = "/",
        ["Roblox: Build A Boat For Treasure"] = "/",
        ["Roblox: Combat Warriors"] = "/",
        ["Roblox: Da Hood"] = "/",
        ["Roblox: Doors"] = "/",
        ["Roblox: Epic Minigames"] = "/",
        ["Roblox: Fisch"] = "/",
        ["Roblox: Funky Friday"] = "/",
        ["Roblox: Grand Piece Online"] = "/",
        ["Roblox: Grow a Garden"] = "/",
        ["Roblox: Islands (Skyblock)"] = "/",
        ["Roblox: Jailbreak"] = "/",
        ["Roblox: Jujutsu Shenanigans"] = "/",
        ["Roblox: King Legacy"] = "/",
        ["Roblox: Livetopia"] = "/",
        ["Roblox: Mad City"] = "/",
        ["Roblox: Mining Simulator 2"] = "/",
        ["Roblox: Pet Simulator X"] = "/",
        ["Roblox: Phantom Forces"] = "/",
        ["Roblox: Piggy"] = "/",
        ["Roblox: Prison Life"] = "/",
        ["Roblox: Project Slayers"] = "/",
        ["Roblox: Restaurant Tycoon 2"] = "/",
        ["Roblox: Rivals"] = "/",
        ["Roblox: Royale High"] = "/",
        ["Roblox: Shindo Life"] = "/",
        ["Roblox: Slap Battles"] = "/",
        ["Roblox: Sonic Speed Simulator"] = "/",
        ["Roblox: Speed Run 4"] = "/",
        ["Roblox: Steal a Brainrot"] = "/",
        ["Roblox: Toilet Tower Defense"] = "/",
        ["Roblox: Tower Defense Simulator"] = "/",
        ["Roblox: Tower of Hell"] = "/",
        ["Roblox: Type Soul"] = "/",
        ["Roblox: Untitled Boxing Game"] = "/",
        ["Roblox: Welcome to Bloxburg"] = "/",
        ["Roblox: Work at a Pizza Place"] = "/",
        ["Roblox: World // Zero"] = "/",
        ["Rohan Online"] = "Enter",
        ["ROSE Online"] = "Enter",
        ["Runes of Magic"] = "Enter",
        ["Ryzom (The Saga of Ryzom)"] = "Enter",
        ["Scrap Mechanic"] = "Enter",
        ["Shell Shockers"] = "Enter",
        ["StarCraft: Remastered"] = "Enter",
        ["StarRupture"] = "Enter",
        ["Staxel"] = "Enter",
        ["Stormworks: Build and Rescue"] = "Enter",
        ["Super Animal Royale"] = "Enter",
        ["Supreme Commander"] = "Enter",
        ["The Escapists 2"] = "Enter",
        ["The Isle (Evrima)"] = "Enter",
        ["The Planet Crafter"] = "Enter",
        ["The Riftbreaker"] = "Enter",
        ["The Sandbox"] = "Enter",
        ["Tibia"] = "Enter",
        ["Titanfall 2"] = "Enter",
        ["Tom Clancy's Ghost Recon Breakpoint"] = "Enter",
        ["Tom Clancy's Rainbow Six Extraction"] = "T",
        ["Tom Clancy's The Division"] = "Enter",
        ["Tom Clancy's The Division 2"] = "Enter",
        ["Total War: Shogun 2"] = "Y",
        ["Town of Salem 2"] = "C",
        ["Trailmakers"] = "Enter",
        ["Ultima Online"] = "Enter",
        ["Ultimate Fishing Simulator"] = "F1",
        ["Undecember"] = "Enter",

        ["WolfTeam"] = "Enter",
        ["Wurm Online"] = "T",
        ["Wurm Unlimited"] = "T",
        ["WWII Online"] = "Enter",
        ["XCOM: Enemy Unknown"] = "J",
        ["Zombie Panic! Source"] = "Y",
        ["ZombsRoyale.io"] = "Enter",
        ["Zwift"] = "M",
        ["War of Rights"] = "Enter",
        ["Warcraft: Orcs & Humans / Warcraft II Remastered"] = "Enter",
        ["Warhammer 40,000: Dawn of War II"] = "Enter",
        ["Warhammer 40,000: Dawn of War III"] = "Enter",
        ["Warhammer 40,000: Dawn of War: Definitive Edition"] = "Enter",
        ["Warhammer: End Times - Vermintide"] = "Enter",
        ["Wizard101"] = "O",
        ["WolfQuest"] = "C",
    };

    /// <summary>Games GENERATED from the source doc's "Excluded" table: the app knows these have no
    /// keyboard-opened text chat box (voice/emote/preset-phrase only, chat behind a mouse click, or no
    /// multiplayer at all). RunTextChat refuses outright for these — same outcome (nothing sent) as a game
    /// absent from both this set and <see cref="Map"/> (the doc's "Needs re-verification" list, merely
    /// UNVERIFIED rather than known-chatless), kept as a separate set only so the trace/spoken message can
    /// say why. Rows the table excludes for other reasons (console-only, shut down, duplicate) are carried
    /// too: they cost nothing, since a game that can't be installed can never own the foreground.</summary>
    private static readonly HashSet<string> NoTextChat = new(StringComparer.OrdinalIgnoreCase)
    {
        "Red Dead Online",
        "The Finals",
        "Escape from Tarkov",
        "Phasmophobia",
        "Ready or Not",
        "Total War: WARHAMMER III",
        "Total War: WARHAMMER II",
        "Total War: ROME II",
        "Fallout 76",
        "Astroneer",
        "RimWorld",
        "XDefiant",
        "Magic: The Gathering Arena",
        "Yu-Gi-Oh! Master Duel",
        "Hearthstone",
        "Legends of Runeterra",
        "Pokémon TCG Live",
        "Marvel Snap",
        "Gwent",
        "Shadowverse: Worlds Beyond",
        "Dota Underlords",
        "Battlegrounds Mobile India",
        "PUBG MOBILE",
        "Mobile Legends: Bang Bang",
        "PlanetSide Arena",
        "Cities: Skylines II",
        "Cities: Skylines",
        "Prison Architect",
        "RollerCoaster Tycoon 3",
        "Planet Coaster 2",
        "Planet Zoo",
        "Farthest Frontier",
        "Manor Lords",
        "Against the Storm",
        "Going Medieval",
        "Banished",
        "Foundation",
        "Workers & Resources: Soviet Republic",
        "Oxygen Not Included",
        "Dyson Sphere Program",
        "Captain of Industry",
        "Shapez 2",
        "Transport Fever 2",
        "Train Sim World 5",
        "Everspace 2",
        "Honkai: Star Rail",
        "Zenless Zone Zero",
        "MechWarrior 5: Mercenaries",
        "Ace Combat 7: Skies Unknown",
        "World of Guns: Gun Disassembly",
        "Fall Guys",
        "Stumble Guys",
        "Content Warning",
        "Peak",
        "Gang Beasts",
        "Dragon Ball: Sparking! ZERO",
        "EA SPORTS UFC 5",
        "God Eater 3",
        "Remnant II",
        "Remnant: From the Ashes",
        "Outriders",
        "State of Decay 2",
        "Construction Simulator",
        "SnowRunner",
        "MudRunner",
        "Riders Republic",
        "Descenders",
        "DiRT Rally 2.0",
        "WRC 24",
        "Need for Speed Heat",
        "Need for Speed Payback",
        "Forza Horizon 4",
        "Forza Horizon 5",
        "BeamNG.drive",
        "Need for Speed Unbound",
        "Gran Turismo 7",
        "Undisputed",
        "Boxing Undisputed",
        "Spectre Divide",
        "Farlight 84",
        "Off The Grid",
        "World of Tanks Modern Armor",
        "Madden NFL 26",
        "Dead by Daylight",
        "EVE Vanguard",
        "MultiVersus",
        "Stronghold Kingdoms",
        "They Are Billions",
        "Sid Meier's Civilization VII",
        "Civilization VI",
        "Football Manager 2025",
        "EA SPORTS FC 25",
        "EA SPORTS FC 26",
        "NBA 2K25",
        "NBA 2K26",
        "Madden NFL 25",
        "F1 24",
        "F1 25",
        "The Crew Motorfest",
        "The Golf Club 2019",
        "EA SPORTS PGA Tour",
        "Combat Master",
        "Bodycam",
        "Move or Die",
        "Dragon Ball FighterZ",
        "THE KING OF FIGHTERS XV",
        "Melty Blood: Type Lumina",
        "NARUTO TO BORUTO: SHINOBI STRIKER",
        "Street Fighter 6",
        "Rivals of Aether",
        "Exoprimal",
        "My Time at Portia",
        "KartRider: Drift",
        "MechWarrior 5: Clans",

        "2XKO",
        "Age of Darkness: Final Stand",
        "Aliens: Fireteam Elite",
        "Animal Jam",
        "ArcheAge",
        "Asheron's Call",
        "Audition Online",
        "Bigscreen",
        "Blade Strangers",
        "Blazing Sails: Pirate Battle Royale",
        "Board Game Arena",
        "Book of Travels",
        "Borderlands: The Pre-Sequel",
        "Brawlout",
        "Battlefield 1942",
        "Battlefield 2",
        "Battlefield 2142",
        "Battlefield: Bad Company 2",
        "ChilloutVR",
        "Circuit Superstars",
        "Club Penguin Rewritten",
        "Contract Wars",
        "Coral Island",
        "Counter-Strike Online",
        "Darkfall: New Dawn",
        "Dead or Alive 5: Last Round",
        "Deceit",
        "Deceive Inc.",
        "Decentraland",
        "Defiance 2050",
        "Dekaron G",
        "Distance",
        "Dread Hunger",
        "Elvenar",
        "Evony: The King's Return",
        "Fantasy Strike",
        "Gaia Online",
        "Granblue Fantasy Versus",
        "Grepolis",
        "Grey Goo",
        "GetAmped 2",
        "Forge of Empires",
        "Furcadia",
        "Galactic Civilizations III",
        "Golf It!",
        "Goodgame Empire",
        "Fight Crab",
        "Fishing: North Atlantic",
        "Fraymakers",
        "From the Depths",
        "Frozen Synapse 2",
        "GT Legends",
        "GTR2",
        "Heroes & Generals",
        "Ikariam",
        "Kingdom of Loathing",
        "KartRider (original PC version)",
        "Kingdoms Reborn",
        "Legend of Mir 2",
        "Lethal League Blaze",
        "Level Zero: Extraction",
        "Life is Feudal: MMO",
        "Lightyear Frontier",
        "Lineage (1998 original)",
        "Luma Island",
        "Marauders",
        "Medal of Honor: Allied Assault",
        "Meta Horizon Worlds",
        "Midnight Ghost Hunt",
        "Mist Survival",
        "League of Angels",
        "Naruto Shippuden: Ultimate Ninja Storm 4",
        "Neos VR",
        "New Fantasy Westward Journey",
        "New Tian Long Ba Bu",
        "Nickelodeon All-Star Brawl 2",
        "O2Jam",
        "OGame",
        "Orcs Must Die 3",
        "Out of the Park Baseball",
        "PBA Pro Bowling 2023",
        "Pirate101",
        "Pocket Bravery",
        "Moviestarplanet",
        "Poker Club",
        "Power Rangers: Battle for the Grid",
        "Propnight",
        "Ranch Simulator",
        "Realm Royale Reforged",
        "PokerStars",
        "Puzzle Pirates",
        "QQ Speed",
        "Richard Burns Rally",
        "Rohan: Blood Feud",
        "Rushdown Revolt",
        "Samurai Shodown (2019)",
        "SCP: Secret Laboratory",
        "Shaiya",
        "SNOW",
        "Soldier of Fortune II: Double Helix",
        "Special Force",
        "Special Force 2",
        "SoulCalibur V",
        "Stormfall: Age of War",
        "Sunkenland",
        "Test Drive Unlimited 2",
        "The Blackout Club",
        "The Outlast Trials",
        "Tian Long Ba Bu",
        "Titanfall",
        "Tom Clancy's Ghost Recon (2001)",
        "Tom Clancy's Rainbow Six 3: Raven Shield",
        "Tom Clancy's Rainbow Six: Vegas 2",
        "Tom Clancy's Splinter Cell: Pandora Tomorrow",
        "Toontown Rewritten",
        "Tooth and Tail",
        "Toram Online",
        "Travian",
        "Tribal Wars",
        "Twilight Struggle",
        "Town of Salem",

        "Zhu Xian Online",
        "Unreal Tournament 4",
        "Utopia",
        "VHS (Video Horror Society)",
        "War for the Overworld",
        "Wargroove 2",
        "Warhammer 40,000: Gladius - Relics of War",
        "Warhammer 40,000: Sanctus Reach",
        "Warhammer Age of Sigmar: Realms of Ruin",
        "Warhaven",
        "Wartune",
        "Webkinz",
        "Werewolves Within",
        "WGT Golf (World Golf Tour)",
        "Wildgate",
    };

    private static readonly HashSet<string> NormalizedNoTextChat =
        [.. NoTextChat.Select(Normalize)];

    /// <summary>Whether this game is KNOWN to have no keyboard-opened text chat. Matched the same
    /// punctuation-loose way as <see cref="Lookup"/>, so a launcher's "Game™: Subtitle" still resolves.
    /// False for a blank or unrecognised name — an unknown game is unverified, not known-chatless.</summary>
    public static bool HasNoTextChat(string? gameName)
    {
        if (string.IsNullOrWhiteSpace(gameName)) return false;
        var norm = Normalize(gameName);
        if (norm.Length == 0) return false;
        if (NormalizedNoTextChat.Contains(norm)) return true;
        // Containment relaxation as in Lookup, so an edition/subtitle difference doesn't defeat the guard —
        // but floored at RelaxedMinimumLength. This list holds names as short as "Peak", and a four-letter
        // substring would condemn every unrelated title that happens to contain it. Lookup can afford the
        // unfloored version because its keys are the ones it would return anyway; here a false match
        // silently disables a working slice.
        foreach (var known in NormalizedNoTextChat)
        {
            if (Math.Min(known.Length, norm.Length) < RelaxedMinimumLength) continue;
            if (known.Contains(norm, StringComparison.Ordinal) || norm.Contains(known, StringComparison.Ordinal))
                return true;
        }
        return false;
    }

    private const int RelaxedMinimumLength = 8;

    // Keyed by the NORMALIZED name (see Normalize), so Lookup is a single dictionary hit for the common
    // case and only falls to the relaxed scan for the "extra punctuation/subtitle" cases (e.g. a
    // launcher's "Call of Duty®: Black Ops 6" vs the table's "Call of Duty: Black Ops 6").
    private static readonly Dictionary<string, string> NormalizedMap = BuildNormalizedMap();

    private static Dictionary<string, string> BuildNormalizedMap()
    {
        var m = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var kv in Map)
        {
            var key = Normalize(kv.Key);
            if (!m.ContainsKey(key)) m[key] = kv.Value;   // first wins; no collisions observed in the source table
        }
        return m;
    }

    /// <summary>Case-insensitive, punctuation-loose match: strip ™/®/: , collapse whitespace, then try an
    /// exact normalized match first and a contains/startswith relaxation second (so "Call of Duty: Black
    /// Ops 6" matches an installed-game name of "Call of Duty Black Ops 6" or vice versa). Null when
    /// <paramref name="gameName"/> is blank or nothing in the table is close enough.</summary>
    public static string? Lookup(string? gameName)
    {
        if (string.IsNullOrWhiteSpace(gameName)) return null;
        var norm = Normalize(gameName);
        if (norm.Length == 0) return null;

        if (NormalizedMap.TryGetValue(norm, out var exact)) return exact;

        // Relaxed pass: whichever direction contains the other (a launcher/storefront name is often a
        // superset — trailing edition/subtitle text — or a subset — a shortened display name).
        foreach (var kv in NormalizedMap)
            if (kv.Key.Contains(norm, StringComparison.Ordinal) || norm.Contains(kv.Key, StringComparison.Ordinal))
                return kv.Value;

        return null;
    }

    /// <summary>Lowercase; drop ™/®; drop ':' (so "Game: Subtitle" and "Game Subtitle" match); collapse
    /// runs of whitespace; trim.</summary>
    private static string Normalize(string s)
    {
        var chars = new System.Text.StringBuilder(s.Length);
        bool lastWasSpace = false;
        foreach (var c in s)
        {
            if (c is '™' or '®' or ':') continue;
            char lower = char.ToLowerInvariant(c);
            bool isSpace = char.IsWhiteSpace(lower);
            if (isSpace && lastWasSpace) continue;
            chars.Append(isSpace ? ' ' : lower);
            lastWasSpace = isSpace;
        }
        return chars.ToString().Trim();
    }
}
