using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace ControllerWheel;

/// <summary>
/// Exports the whole Help system as a static, upload-ready website — one page per language, laid out and
/// coloured to mesh with getradiata.app (it links that site's <c>styles.css</c> and reuses its
/// <c>.wrap</c> / <c>.card</c> / <c>footer</c> classes, so a retone of the site carries the help with it).
/// <para>Generated by <c>Radiata.exe --export-help-html [dir]</c>, exactly as <c>CONTROLS.md</c> is
/// generated by <c>--export-controls</c> — the same source, a different surface. Never hand-edit the
/// output; edit <see cref="HelpContent"/> (and the <c>HelpText*</c> maps) and re-export.</para>
/// <para>Two things it does that the Markdown export can't: it draws the <see cref="HelpFigures"/>
/// illustrations as inline SVG (they're pure data, so this needs no WPF), and it carries all four
/// languages. LiveOnly blocks are skipped for the same reason the Markdown export skips them — they
/// describe the reader's own bindings, which a web page can't know.</para>
/// </summary>
public static class HelpHtmlExport
{
    /// <summary>Last-resort cache-buster on the site's shared <c>styles.css</c>. Must equal the <c>?v=</c>
    /// the marketing pages carry (the harness `locregress` group compares them): the Help pages and the
    /// site share one stylesheet, so a lower value here keeps a browser on stale CSS for /help/ alone.
    /// ⚠ Bump it whenever the site's <c>styles.css</c> link moves. It is only used when the export target
    /// is not inside the site tree and no <c>--css-version</c> was given — see <see cref="ResolveStylesVersion"/>.</summary>
    public const int SiteStylesVersion = 43;

    /// <summary>Cache-busters on the site's other two shared assets, matched to what the marketing pages
    /// link. They are fixed rather than sniffed because neither is referenced from the site's root page in
    /// a form the stylesheet sniff could read. ⚠ Bump each one whenever the site's own link moves, or a
    /// browser holding the previous copy keeps it on /help/ alone.</summary>
    public const int SiteFaviconVersion = 2;
    public const int SiteKofiVersion = 5;

    /// <summary>The <c>?v=</c> the pages will link. Precedence: an explicit value (the CLI's
    /// <c>--css-version=N</c>), then the version the site's own root <c>index.html</c> links when the export
    /// lands one level under the site root (the normal deployment), then <see cref="SiteStylesVersion"/>.
    /// Sniffing the site keeps the Help pages in step with every other page without a second constant.</summary>
    public static int ResolveStylesVersion(string dir, int? explicitVersion)
    {
        if (explicitVersion is int v) return v;
        try
        {
            var root = Path.Combine(Path.GetFullPath(dir), "..", "index.html");
            if (File.Exists(root))
            {
                var m = SiteStylesLink.Match(File.ReadAllText(root));
                if (m.Success && int.TryParse(m.Groups[1].Value, out var sniffed)) return sniffed;
            }
        }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }
        return SiteStylesVersion;
    }

    private static readonly Regex SiteStylesLink = new(@"styles\.css\?v=(\d+)", RegexOptions.Compiled);

    /// <summary>Page file name per language code; English is the folder's index.</summary>
    private static string FileFor(string code) => code == HelpLocalization.DefaultCode ? "index.html" : code + ".html";

    /// <summary>Root-absolute URL of a Help page, as the site's own nav writes it.</summary>
    private static string HelpHref(string code) => code == HelpLocalization.DefaultCode ? "/help/" : $"/help/{code}.html";

    /// <summary>Root-absolute URL of a hand-maintained site page (<paramref name="folder"/> is "" for the
    /// home page, else e.g. "download"). Every page on the site has one file per language, English as index.</summary>
    private static string SiteHref(string folder, string code)
    {
        string f = folder.Length == 0 ? "/" : $"/{folder}/";
        return code == HelpLocalization.DefaultCode ? f : (folder.Length == 0 ? $"/{code}.html" : $"{f}{code}.html");
    }

    /// <summary>The site chrome the exporter reproduces around the topics — nav labels, footer, masthead and
    /// metadata. These must match the hand-maintained pages (<c>/download/&lt;lang&gt;.html</c> is the
    /// reference), so they live here beside the site contract rather than in the app's Help maps: the app
    /// never shows them, and the parity check must not treat them as untranslated Help. Menu-path segments
    /// in the subtitle are the app's own localized names; Arabic uses <c>◂</c> as the separator like the
    /// app's RTL paths do.</summary>
    private sealed record SiteChrome(
        string Title, string Heading, string Subtitle, string Description,
        string NavSite, string NavDownload, string NavHelp, string NavDonate, string NavLanguage, string FooterHome);

    private static readonly Dictionary<string, SiteChrome> SiteChromes = new(StringComparer.Ordinal)
    {
        ["en"] = new("Help", "Radiata Help",
            "Every topic from the app's <strong>Settings ▸ Help</strong> tab.",
            "Every Help topic from Radiata, the controller-first command center for Windows.",
            "Site", "Download", "Help", "Donate ♥", "Language", "Home"),
        ["es"] = new("Ayuda", "Ayuda de Radiata",
            "Todos los temas de la pestaña <strong>Ajustes ▸ Ayuda</strong> de la aplicación.",
            "Todos los temas de ayuda de Radiata, el centro de comandos para Windows que se maneja con el mando.",
            "Sitio", "Descargar", "Ayuda", "Donar ♥", "Idioma", "Inicio"),
        ["de"] = new("Hilfe", "Radiata-Hilfe",
            "Alle Themen aus dem Tab <strong>Einstellungen ▸ Hilfe</strong> der App.",
            "Alle Hilfethemen von Radiata, der Controller-first-Kommandozentrale für Windows.",
            "Website", "Download", "Hilfe", "Spenden ♥", "Sprache", "Startseite"),
        ["ja"] = new("ヘルプ", "Radiata ヘルプ",
            "アプリの <strong>設定 ▸ ヘルプ</strong> タブにあるすべての項目。",
            "Windows 向けのコントローラー優先コマンドセンター Radiata の、すべてのヘルプ項目。",
            "サイト", "ダウンロード", "ヘルプ", "寄付 ♥", "言語", "ホーム"),
        ["ar"] = new("المساعدة", "مساعدة Radiata",
            "كل المواضيع من تبويب <strong>الإعدادات ◂ المساعدة</strong> في التطبيق.",
            "كل مواضيع مساعدة Radiata، مركز الأوامر لنظام Windows الذي يُدار بوحدة التحكم أولًا.",
            "الموقع", "تنزيل", "المساعدة", "تبرّع ♥", "اللغة", "الصفحة الرئيسية"),
    };

    /// <summary>The Workshop nav label per language. The /workshop/ pages document the package features
    /// <see cref="ReleaseGates"/> withholds, so every site page — hand-maintained and generated — carries this
    /// link commented out, in the same slot, until the Workshop launches.</summary>
    private static readonly Dictionary<string, string> NavWorkshop = new(StringComparer.Ordinal)
    {
        ["en"] = "Workshop", ["es"] = "Taller", ["de"] = "Werkstatt", ["ja"] = "ワークショップ", ["ar"] = "الورشة",
    };

    private static SiteChrome ChromeFor(string code) =>
        SiteChromes.TryGetValue(code, out var c) ? c : SiteChromes[HelpLocalization.DefaultCode];

    /// <summary>Shipping languages — the pseudo-locales are dev-only and never exported or linked.</summary>
    private static IEnumerable<HelpLanguage> Shipping() =>
        HelpLocalization.Languages.Where(l => !l.Code.StartsWith("qps", StringComparison.Ordinal));

    /// <summary>Where the export is served from. The pages already assume this site (they link its
    /// <c>../styles.css</c>); search engines need the same assumption spelled out as absolute alternates.</summary>
    private const string SiteHelpUrl = "https://getradiata.app/help/";

    /// <summary>One <c>rel="alternate" hreflang</c> per language plus <c>x-default</c> (English) — the signal
    /// that these pages are translations of each other rather than duplicates.</summary>
    private static string Alternates()
    {
        var sb = new StringBuilder();
        foreach (var l in Shipping())
            sb.Append($"<link rel=\"alternate\" hreflang=\"{l.Code}\" href=\"{SiteHelpUrl}{FileFor(l.Code)}\">\n");
        sb.Append($"<link rel=\"alternate\" hreflang=\"x-default\" href=\"{SiteHelpUrl}{FileFor(HelpLocalization.DefaultCode)}\">");
        return sb.ToString();
    }

    /// <summary>Write the whole site into <paramref name="dir"/>. Flat on purpose — every page sits beside
    /// its siblings, so one relative <c>../styles.css</c> is correct for all of them and the folder can be
    /// dropped anywhere one level under the site root. Every other site reference (favicon, logo, nav,
    /// Ko-fi loader) is root-absolute, so the folder must sit exactly one level down.</summary>
    public static void Write(string dir, int? cssVersion = null)
    {
        Directory.CreateDirectory(dir);
        int v = ResolveStylesVersion(dir, cssVersion);
        foreach (var lang in Shipping())
            File.WriteAllText(Path.Combine(dir, FileFor(lang.Code)), Page(lang.Code, v), new UTF8Encoding(false));
    }

    // ── Glyphs the web can't show ───────────────────────────────────────────────

    /// <summary>Authored Help uses the heavy D-pad arrows from Supplemental Arrows-C, which the app's own
    /// font covers but no default Windows or Android UI font does — a browser shows tofu. The web export
    /// downgrades them to the plain arrows every system font carries. Keyed by the surrogate pair, since
    /// these are astral code points.</summary>
    private static readonly (string From, string To)[] WebGlyphs =
    [
        ("\U0001F844", "←"), ("\U0001F845", "↑"), ("\U0001F846", "→"), ("\U0001F847", "↓"),
    ];

    /// <summary>Blocks with essentially no system-font coverage: Geometric Shapes Extended, Supplemental
    /// Arrows-C, Symbols for Legacy Computing. Nothing in them may reach the exported HTML.</summary>
    private static bool IsUnrenderable(int cp) =>
        cp is >= 0x1F780 and <= 0x1F8FF or >= 0x1FB00 and <= 0x1FBFF;

    /// <summary>The final pass over a page: substitute the known arrows, then refuse to emit anything else
    /// from the unrenderable blocks. Failing the export beats shipping tofu that is only noticed live.</summary>
    internal static string ForWeb(string page)
    {
        // Raw string literals carry the source file's CRLF while AppendLine emits the platform's; the site
        // is LF throughout, so one ending for the whole page.
        page = page.Replace("\r\n", "\n", StringComparison.Ordinal);
        foreach (var (from, to) in WebGlyphs) page = page.Replace(from, to, StringComparison.Ordinal);
        for (int i = 0; i < page.Length; i++)
        {
            if (!char.IsHighSurrogate(page[i]) || i + 1 >= page.Length) continue;
            int cp = char.ConvertToUtf32(page[i], page[i + 1]);
            if (IsUnrenderable(cp))
                throw new InvalidOperationException(
                    $"Help HTML export: U+{cp:X} has no browser font coverage — add it to HelpHtmlExport.WebGlyphs or change the source text.");
            i++;
        }
        return page;
    }

    // ── The page ────────────────────────────────────────────────────────────────

    private static string Page(string code, int cssVersion)
    {
        var topics = HelpLocalization.Topics(code);
        var sb = new StringBuilder(256 * 1024);

        sb.Append(Head(code, cssVersion));
        sb.Append(Nav(code));
        sb.Append(Masthead(code));

        sb.AppendLine("<div class=\"helpwrap\">");
        sb.AppendLine("<nav class=\"toc\" aria-label=\"Contents\"><div class=\"toc-inner\">");
        foreach (var cat in HelpContent.CategoryOrder)
        {
            var inCat = topics.Where(t => t.Category == cat).ToList();
            if (inCat.Count == 0) continue;
            sb.AppendLine($"  <h2>{Esc(HelpLocalization.Text(code, cat))}</h2>");
            sb.AppendLine("  <ul>");
            foreach (var t in inCat)
                sb.AppendLine($"    <li data-topic=\"{Esc(t.Id)}\"><a href=\"#{Esc(t.Id)}\">{IsolateArrows(Esc(t.Title))}</a></li>");
            sb.AppendLine("  </ul>");
        }
        sb.AppendLine("</div></nav>");

        sb.AppendLine("<main class=\"topics\">");
        sb.AppendLine($"  <p class=\"nomatch\" hidden>{Esc(HelpLocalization.Text(code, HelpLocalization.Chrome.NoMatch))}</p>");
        foreach (var cat in HelpContent.CategoryOrder)
        {
            foreach (var t in topics.Where(t => t.Category == cat))
            {
                sb.AppendLine($"  <article class=\"topic\" id=\"{Esc(t.Id)}\">");
                sb.AppendLine($"    <h2>{IsolateArrows(Esc(t.Title))}</h2>");
                sb.Append(Body(t, code));
                sb.AppendLine("  </article>");
            }
        }
        sb.AppendLine("</main>");
        sb.AppendLine("</div>");

        sb.Append(Footer(code));
        sb.Append(Script(SearchIndex(topics)));
        // The shared Ko-fi loader draws the floating tip button; label, colours and position live in that
        // one file, so nothing about the widget is copied here. Deferred and async: an unreachable
        // ko-fi.com draws nothing and blocks nothing.
        sb.AppendLine($"<script src=\"/assets/kofi.js?v={SiteKofiVersion}\" defer></script>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        return ForWeb(sb.ToString());
    }

    /// <summary>A topic's blocks. A run of bullets becomes one real list, nested by <c>Indent</c> — a
    /// deeper bullet's list opens inside its parent's <c>&lt;li&gt;</c>, which is the only nesting HTML
    /// actually defines (a bare <c>&lt;ul&gt;</c> inside a <c>&lt;ul&gt;</c> renders but doesn't parse as a
    /// sublist, so screen readers and outline tools lose the relationship).</summary>
    private static string Body(HelpTopic t, string code)
    {
        var sb = new StringBuilder();
        var run = new List<HelpBlock>();          // the bullet run still being collected
        void FlushBullets()
        {
            if (run.Count == 0) return;
            int i = 0;
            sb.Append(RenderList(run, ref i, 0, code, 4));
            run.Clear();
        }

        foreach (var b in t.Body)
        {
            if (b.LiveOnly) continue;   // describes the reader's own bindings — see the class remarks
            if (b.Kind == HelpBlockKind.Bullet) { run.Add(b); continue; }
            FlushBullets();
            var html = Inline(b.Text, code);

            switch (b.Kind)
            {
                case HelpBlockKind.Para:    sb.AppendLine($"    <p>{html}</p>"); break;
                case HelpBlockKind.Heading: sb.AppendLine($"    <h3>{html}</h3>"); break;
                case HelpBlockKind.Tip:     sb.AppendLine($"    <p class=\"note tip\">{html}</p>"); break;
                case HelpBlockKind.Warning: sb.AppendLine($"    <p class=\"note warn\">{html}</p>"); break;
                case HelpBlockKind.Figure:
                    sb.AppendLine("    <figure>");
                    if (HelpFigures.ById(b.Figure) is { } fig) sb.AppendLine(Svg(fig, code));
                    sb.AppendLine($"      <figcaption>{html}</figcaption>");
                    sb.AppendLine("    </figure>");
                    break;
            }
        }
        FlushBullets();
        return sb.ToString();
    }

    /// <summary>One <c>&lt;ul&gt;</c> of the bullets at <paramref name="depth"/>, recursing into any deeper
    /// run that follows an item. <paramref name="i"/> walks the whole run, so the caller gets the entire
    /// tree from one call. An item's sublist is emitted before its <c>&lt;/li&gt;</c>.</summary>
    private static string RenderList(List<HelpBlock> run, ref int i, int depth, string code, int pad)
    {
        var sb = new StringBuilder();
        string ind = new(' ', pad);
        sb.AppendLine($"{ind}<ul>");
        while (i < run.Count && run[i].Indent >= depth)
        {
            if (run[i].Indent > depth)
            {
                // A deeper bullet with no parent at this level can't happen in authored content, but it
                // must not drop the item — treat it as belonging to the level it landed on.
                sb.Append(RenderList(run, ref i, depth + 1, code, pad + 4));
                continue;
            }
            var item = Inline(run[i].Text, code);
            i++;
            if (i < run.Count && run[i].Indent > depth)
            {
                sb.AppendLine($"{ind}  <li>{item}");
                sb.Append(RenderList(run, ref i, depth + 1, code, pad + 4));
                sb.AppendLine($"{ind}  </li>");
            }
            else sb.AppendLine($"{ind}  <li>{item}</li>");
        }
        sb.AppendLine($"{ind}</ul>");
        return sb.ToString();
    }

    // ── Inline markup ───────────────────────────────────────────────────────────

    private static readonly Regex CrossLink = new(@"\[\[([^\]|]+)\|([^\]]+)\]\]|\[\[([^\]|]+)\]\]", RegexOptions.Compiled);
    private static readonly Regex MdLink    = new(@"\[([^\]]+)\]\(([^)]+)\)", RegexOptions.Compiled);
    private static readonly Regex Bold      = new(@"\*\*(.+?)\*\*", RegexOptions.Compiled);
    private static readonly Regex Code      = new(@"`([^`]+)`", RegexOptions.Compiled);

    /// <summary>The D-pad arrow pair names physical buttons and is never mirrored, so on an RTL page it is
    /// wrapped as a left-to-right island (a <c>dir</c> attribute isolates in every browser). The same rule the
    /// app applies in <c>InlineMarkup.IsolateArrows</c>; the pair is plain text, so this runs after escaping.
    /// ⚠ Visible text only — never the search index, whose strings are matched, not rendered.</summary>
    private static string IsolateArrows(string html) => html.Replace("🡄 🡆", "<span dir=\"ltr\">🡄 🡆</span>");

    /// <summary>Authored inline markup → HTML. Order matters: escape first (so authored text can't inject
    /// markup), then substitute, so every tag this emits is one it wrote itself.</summary>
    private static string Inline(string text, string code)
    {
        var s = IsolateArrows(Esc(HelpContent.ResolveTokens(text, HelpContent.ExportToken)));
        // A cross-link's target is a topic id, and every topic is a section of this one page.
        s = CrossLink.Replace(s, m =>
        {
            string id = m.Groups[1].Success ? m.Groups[1].Value : m.Groups[3].Value;
            string label = m.Groups[2].Success ? m.Groups[2].Value : m.Groups[3].Value;
            return $"<a href=\"#{id}\">{label}</a>";
        });
        // Authored external links only ever point at documented sites; rel keeps the opener safe anyway.
        s = MdLink.Replace(s, m => $"<a href=\"{m.Groups[2].Value}\" target=\"_blank\" rel=\"noopener\">{m.Groups[1].Value}</a>");
        s = Bold.Replace(s, "<strong>$1</strong>");
        s = Code.Replace(s, "<code>$1</code>");
        return s;
    }

    // ── Figures → inline SVG ────────────────────────────────────────────────────

    /// <summary>Ink role → CSS colour. Roles resolve against the site's own custom properties, so the
    /// diagrams retone with the site exactly as they retone with the app.</summary>
    private static string Colour(FigInk ink) => ink switch
    {
        FigInk.Body       => "var(--ink,#1c1e2b)",
        FigInk.Muted      => "var(--muted,#6b6f7d)",
        FigInk.Faint      => "var(--line,#e6e7ec)",
        FigInk.Surface    => "var(--card,#ffffff)",
        FigInk.Accent     => "var(--accent,#E07A5F)",
        FigInk.AccentSoft => "rgba(224,122,95,.18)",
        FigInk.Warn       => "#B4543C",
        _                 => "none",
    };

    private static string Num(double d) => d.ToString("0.##", CultureInfo.InvariantCulture);

    /// <summary>One figure as a self-contained, responsive SVG. The viewBox is the figure's own abstract
    /// canvas, so the browser does the scaling the WPF renderer does by hand.</summary>
    private static string Svg(HelpFigure fig, string code)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"      <svg class=\"fig\" viewBox=\"0 0 {Num(fig.Width)} {Num(fig.Height)}\" "
                      + $"width=\"{Num(fig.Width)}\" role=\"img\" xmlns=\"http://www.w3.org/2000/svg\">");
        bool rtl = HelpLocalization.Language(code).Rtl, mirrored = fig.Mirrored(rtl);
        foreach (var p in fig.PartsFor(rtl)) sb.Append(Part(p, code, mirrored));
        sb.AppendLine("      </svg>");
        return sb.ToString();
    }

    private static string Part(FigPart p, string code, bool mirrored)
    {
        string stroke = Colour(p.Ink), fill = Colour(p.Fill);
        string dash = p.Dashed ? " stroke-dasharray=\"4 3\"" : "";
        const string ind = "        ";

        switch (p.Shape)
        {
            case FigShape.Rect:
                return $"{ind}<rect x=\"{Num(p.X)}\" y=\"{Num(p.Y)}\" width=\"{Num(p.W)}\" height=\"{Num(p.H)}\" "
                     + $"rx=\"{Num(p.R)}\" fill=\"{fill}\" stroke=\"{stroke}\"{dash}/>\n";

            case FigShape.Ellipse:
                return $"{ind}<ellipse cx=\"{Num(p.X + p.W / 2)}\" cy=\"{Num(p.Y + p.H / 2)}\" "
                     + $"rx=\"{Num(p.W / 2)}\" ry=\"{Num(p.H / 2)}\" fill=\"{fill}\" stroke=\"{stroke}\"{dash}/>\n";

            case FigShape.Wedge:
                return $"{ind}<path d=\"{WedgePath(p)}\" fill=\"{fill}\" stroke=\"{stroke}\"{dash}/>\n";

            case FigShape.Line:
                return $"{ind}<line x1=\"{Num(p.X)}\" y1=\"{Num(p.Y)}\" x2=\"{Num(p.X2)}\" y2=\"{Num(p.Y2)}\" "
                     + $"stroke=\"{stroke}\"{dash}/>\n";

            case FigShape.Arrow:
                return $"{ind}<line x1=\"{Num(p.X)}\" y1=\"{Num(p.Y)}\" x2=\"{Num(p.X2)}\" y2=\"{Num(p.Y2)}\" "
                     + $"stroke=\"{stroke}\"{dash}/>\n"
                     + $"{ind}<path d=\"{ArrowHead(p)}\" fill=\"{stroke}\" stroke=\"none\"/>\n";

            case FigShape.Text:
                return Text(p, code, ind, mirrored);
        }
        return "";
    }

    /// <summary>Annulus sector. <c>From</c>/<c>Sweep</c> are degrees clockwise from 12 o'clock — the
    /// wheel's own convention — so a point at angle θ is (cx + r·sin θ, cy − r·cos θ).</summary>
    private static string WedgePath(FigPart p)
    {
        double cx = p.X, cy = p.Y, inner = p.R, outer = p.W, a0 = p.From, a1 = p.From + p.Sweep;
        (double x, double y) At(double r, double deg)
        {
            double rad = deg * Math.PI / 180.0;
            return (cx + r * Math.Sin(rad), cy - r * Math.Cos(rad));
        }
        var (ox0, oy0) = At(outer, a0);
        var (ox1, oy1) = At(outer, a1);
        var (ix1, iy1) = At(inner, a1);
        var (ix0, iy0) = At(inner, a0);
        int large = Math.Abs(p.Sweep) > 180 ? 1 : 0;
        return $"M {Num(ox0)} {Num(oy0)} A {Num(outer)} {Num(outer)} 0 {large} 1 {Num(ox1)} {Num(oy1)} "
             + $"L {Num(ix1)} {Num(iy1)} A {Num(inner)} {Num(inner)} 0 {large} 0 {Num(ix0)} {Num(iy0)} Z";
    }

    private static string ArrowHead(FigPart p)
    {
        double dx = p.X2 - p.X, dy = p.Y2 - p.Y;
        double len = Math.Sqrt(dx * dx + dy * dy);
        if (len < 0.001) return "";
        dx /= len; dy /= len;
        const double h = 7, w = 3.6;                  // head length and half-width
        double bx = p.X2 - dx * h, by = p.Y2 - dy * h;
        return $"M {Num(p.X2)} {Num(p.Y2)} L {Num(bx - dy * w)} {Num(by + dx * w)} "
             + $"L {Num(bx + dy * w)} {Num(by - dx * w)} Z";
    }

    /// <summary>A wrapped text part. Width is estimated rather than measured — there is no font engine
    /// here — which is why <c>W</c> is treated as a soft limit: a long word is never broken, it just runs
    /// a little wide. Literal parts (key, file and code names) are never translated and always run left to
    /// right — see <see cref="FigPart.Literal"/>.</summary>
    private static string Text(FigPart p, string code, string ind, bool mirrored)
    {
        string raw = HelpContent.ResolveTokens(
            p.Literal ? p.Text ?? "" : HelpLocalization.Text(code, p.Text ?? ""), HelpContent.ExportToken);
        var lines = Wrap(raw, p.W, p.Size);

        bool pageRtl = HelpLocalization.Language(code).Rtl, rtl = pageRtl && !p.Literal;
        // A TopLeft label hugs its box's authored left edge, or the right edge once the figure is mirrored,
        // whatever its script. SVG 'start' follows the text's direction, so the physical edge takes 'start' or
        // 'end' depending on it.
        bool hugRight = mirrored;
        string anchor = p.Anchor != FigAnchor.TopLeft ? "middle" : hugRight != rtl ? "end" : "start";
        double ax = p.Anchor == FigAnchor.TopLeft && hugRight ? p.X + p.W : p.X;
        double lineH = p.Size * 1.25;
        // TopCenter/TopLeft put the first line's baseline just below Y; MiddleCenter centres the whole
        // block on Y, which is what a label inside a shape needs.
        double first = p.Anchor == FigAnchor.MiddleCenter
            ? p.Y - (lines.Count - 1) * lineH / 2 + p.Size * 0.35
            : p.Y + p.Size * 0.95;

        var sb = new StringBuilder();
        sb.Append($"{ind}<text x=\"{Num(ax)}\" y=\"{Num(first)}\" fill=\"{Colour(p.Ink)}\" "
                  + $"font-size=\"{Num(p.Size)}\" text-anchor=\"{anchor}\"");
        if (p.Bold) sb.Append(" font-weight=\"600\"");
        // Explicit on an RTL page even for a literal: an SVG label otherwise inherits the page's dir="rtl".
        if (pageRtl) sb.Append(rtl ? " direction=\"rtl\"" : " direction=\"ltr\"");
        sb.Append(">");
        for (int i = 0; i < lines.Count; i++)
            sb.Append($"<tspan x=\"{Num(ax)}\"{(i == 0 ? "" : $" dy=\"{Num(lineH)}\"")}>{Esc(lines[i])}</tspan>");
        sb.AppendLine("</text>");
        return sb.ToString();
    }

    /// <summary>Full-width scripts advance about one em per glyph where Latin averages roughly half, so a
    /// character count is not a width. This is the whole reason the wrapper measures instead of counting:
    /// a Japanese label wrapped on Latin metrics runs off the canvas.</summary>
    private static double Advance(char c, double size) => IsWide(c) ? size : size * 0.54;

    /// <summary>CJK and the full-width forms — the ranges that advance a full em and may break between any
    /// two characters, since they carry no spaces.</summary>
    public static bool IsWide(char c) =>
        c is >= 'ᄀ' and <= 'ᇿ'      // Hangul Jamo
          or >= '⺀' and <= '〿'      // CJK radicals + punctuation
          or >= '぀' and <= 'ヿ'      // kana
          or >= '㐀' and <= '䶿'      // CJK ext A
          or >= '一' and <= '鿿'      // CJK unified
          or >= '가' and <= '힯'      // Hangul syllables
          or >= '豈' and <= '﫿'      // CJK compatibility
          or >= '＀' and <= '｠';     // full-width forms

    /// <summary>Greedy wrap against an estimated advance width (there is no font engine here, which is why
    /// <c>W</c> is a soft limit). Latin breaks at spaces and never splits a word; full-width runs break
    /// between characters, but not before a closing bracket or Japanese punctuation, which may not open a
    /// line.</summary>
    private static List<string> Wrap(string text, double width, double size)
    {
        if (width <= 0 || text.Length == 0) return [text];
        if (text.Sum(c => Advance(c, size)) <= width) return [text];

        const string noStart = "、。，．）」』】〕〉》”’!?！？:;：；ー…";
        var lines = new List<string>();
        var cur = new StringBuilder();
        double w = 0;
        int lastSpace = -1;      // index within cur of the last space, for Latin back-off
        double widthAt = 0;      // accumulated width up to that space

        foreach (var c in text)
        {
            double a = Advance(c, size);
            if (w + a > width && cur.Length > 0)
            {
                if (IsWide(c) && !noStart.Contains(c))
                {
                    lines.Add(cur.ToString()); cur.Clear(); w = 0; lastSpace = -1;
                }
                else if (lastSpace > 0)
                {
                    lines.Add(cur.ToString(0, lastSpace));
                    var rest = cur.ToString(lastSpace + 1, cur.Length - lastSpace - 1);
                    cur.Clear(); cur.Append(rest);
                    w -= widthAt + Advance(' ', size);
                    lastSpace = -1;
                }
                // else: one unbreakable run wider than the canvas — let it overhang rather than split a word.
            }
            if (c == ' ') { lastSpace = cur.Length; widthAt = w; }
            cur.Append(c);
            w += a;
        }
        if (cur.Length > 0) lines.Add(cur.ToString());
        return lines;
    }

    // ── Search index ────────────────────────────────────────────────────────────

    /// <summary>The same haystack <see cref="HelpContent.Search"/> uses — title, keywords and body — as a
    /// JSON array the page's own filter reads. Keywords are the union of the translated and English sets
    /// for the same reason the in-app search unions them: an English term has to keep finding its topic.</summary>
    private static string SearchIndex(IReadOnlyList<HelpTopic> topics)
    {
        var sb = new StringBuilder("[");
        for (int i = 0; i < topics.Count; i++)
        {
            var t = topics[i];
            var en = HelpContent.Topics.FirstOrDefault(s => s.Id == t.Id);
            var hay = string.Join(' ', new[] { t.Title, t.Keywords, en?.Title ?? "", en?.Keywords ?? "" }
                                       .Concat(t.Body.Select(b => b.Text)));
            if (i > 0) sb.Append(',');
            sb.Append($"{{\"id\":{JsonStr(t.Id)},\"t\":{JsonStr(hay.ToLowerInvariant())}}}");
        }
        return sb.Append(']').ToString();
    }

    private static string JsonStr(string s)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in s)
            sb.Append(c switch
            {
                '"'  => "\\\"",
                '\\' => "\\\\",
                '\n' or '\r' or '\t' => " ",
                '<'  => "\\u003c",          // can't close the enclosing <script>
                _ => c < ' ' ? " " : c.ToString(),
            });
        return sb.Append('"').ToString();
    }

    private static string Esc(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    // ── Page furniture ──────────────────────────────────────────────────────────

    /// <summary>Title follows the site's <c>Radiata — &lt;page&gt;</c> pattern; the language is carried by
    /// <c>lang</c> and the hreflang alternates, never named in the title. The favicon is the site's shared
    /// file — the same drawing as the page logo — never an inline approximation of the mark.</summary>
    private static string Head(string code, int cssVersion) => $"""
        <!DOCTYPE html>
        <html lang="{code}"{(HelpLocalization.Language(code).Rtl ? " dir=\"rtl\"" : "")}>
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Radiata — {Esc(ChromeFor(code).Title)}</title>
        <meta name="description" content="{Esc(ChromeFor(code).Description)}">
        {Alternates()}
        <!-- GENERATED by Radiata.exe --export-help-html from Core/HelpContent.cs — do NOT hand-edit. -->
        <link rel="icon" type="image/svg+xml" href="/assets/favicon.svg?v={SiteFaviconVersion}">
        <link rel="stylesheet" href="../styles.css?v={cssVersion}">
        <style>
        {Css()}
        </style>
        </head>
        <body class="helppage" style="--accent:#E07A5F">
        """ + "\n";

    /// <summary>The site's shared four-item nav with the language switcher at its trailing end — the same
    /// markup every hand-maintained page carries, so the shared sheet styles it (<c>.sitenav .langs</c>
    /// positions the switcher; add none here). Nested <c>&lt;nav&gt;</c>s are intentional: each carries its
    /// own label, so assistive tech announces "Site" and "Language" separately.</summary>
    private static string Nav(string code)
    {
        var c = ChromeFor(code);
        var sb = new StringBuilder();
        sb.AppendLine($"<nav class=\"sitenav\" aria-label=\"{Esc(c.NavSite)}\">");
        sb.AppendLine("  <div class=\"wrap\">");
        sb.AppendLine($"    <a href=\"{SiteHref("", code)}\">Radiata</a>");
        sb.AppendLine($"    <a href=\"{SiteHref("download", code)}\">{Esc(c.NavDownload)}</a>");
        sb.AppendLine($"    <a href=\"{HelpHref(code)}\" aria-current=\"page\">{Esc(c.NavHelp)}</a>");
        sb.AppendLine($"    <!-- <a href=\"{SiteHref("workshop", code)}\">{Esc(NavWorkshop.GetValueOrDefault(code, NavWorkshop["en"]))}</a> -->");
        sb.AppendLine($"    <a href=\"{SiteHref("tip", code)}\">{Esc(c.NavDonate)}</a>");
        sb.AppendLine($"    <nav class=\"langs\" aria-label=\"{Esc(c.NavLanguage)}\">");
        sb.Append("      ");
        foreach (var l in Shipping())
            sb.Append($"<a href=\"{HelpHref(l.Code)}\"{(l.Code == code ? " aria-current=\"page\"" : "")}>{Esc(l.NativeName)}</a>");
        sb.AppendLine();
        sb.AppendLine("    </nav>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</nav>");
        return sb.ToString();
    }

    /// <summary>Help-only additions on top of the site's shared sheet. Every colour goes through the site's
    /// custom properties with a fallback, so this file renders correctly even if styles.css is missing.</summary>
    private static string Css() => """
        /* The page background wheel belongs to the marketing page; a long reference page with a sticky
           sidebar scrolls past it, so it's suppressed here rather than tiled behind the text. */
        body.helppage::after{display:none}
        .helphead{background:#eceef2;border-bottom:1px solid var(--line,#e6e7ec);padding:26px 0 22px}
        .helphead .row{display:flex;align-items:center;gap:16px;flex-wrap:wrap}
        .helphead img{width:44px;height:44px;flex:0 0 auto}
        .helphead h1{margin:0;font-size:clamp(22px,3.2vw,30px);letter-spacing:-.02em;color:var(--navy,#3D405B)}
        .helphead p{margin:2px 0 0;color:var(--muted,#6b6f7d);font-size:13.5px}
        .searchrow{margin-top:16px}
        .searchrow input{width:100%;max-width:420px;font:inherit;font-size:14.5px;padding:9px 13px;
          border:1px solid var(--line,#e6e7ec);border-radius:10px;background:#fff;color:inherit}
        .searchrow input:focus{outline:2px solid var(--accent,#E07A5F);outline-offset:1px;border-color:transparent}

        .helpwrap{max-width:1180px;margin:0 auto;padding:0 24px;display:grid;
          grid-template-columns:250px minmax(0,1fr);gap:38px;align-items:start}
        /* The site nav is sticky (--nav-h in styles.css), so the rail and every anchor target clear it;
           a flat offset is only right on a page with no nav. */
        .toc{position:sticky;top:calc(var(--nav-h) + 18px);max-height:calc(100vh - var(--nav-h) - 36px);overflow:auto;padding:26px 0 40px}
        .toc h2{font-size:11.5px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted,#6b6f7d);
          margin:20px 0 7px;font-weight:600}
        .toc h2:first-child{margin-top:0}
        .toc ul{list-style:none;margin:0;padding:0}
        .toc li{margin:1px 0}
        .toc a{display:block;text-decoration:none;font-size:14px;color:var(--ink,#1c1e2b);
          padding:4px 9px;border-radius:7px;border-left:2px solid transparent}
        .toc a:hover{background:rgba(20,22,34,.05)}
        .toc a[aria-current]{border-left-color:var(--accent,#E07A5F);background:rgba(224,122,95,.10);font-weight:600}

        .topics{padding:26px 0 20px;min-width:0}
        .nomatch{color:var(--muted,#6b6f7d)}
        .topic{border:1px solid var(--line,#e6e7ec);border-radius:14px;background:var(--card,#fff);
          padding:22px 24px;margin:0 0 18px;scroll-margin-top:calc(var(--nav-h) + 18px)}
        .topic h2{margin:0 0 12px;font-size:21px;letter-spacing:-.01em;color:var(--navy,#3D405B)}
        .topic h3{margin:20px 0 8px;font-size:15px;color:var(--navy,#3D405B)}
        .topic p{margin:0 0 11px}
        .topic ul{margin:0 0 11px;padding-left:20px}
        .topic li{margin:5px 0}
        .topic li ul{margin:5px 0 0}
        .topic a{color:var(--navy,#3D405B);text-decoration:underline;text-underline-offset:2px}
        .topic a:hover{color:var(--accent,#E07A5F)}
        .note{border-radius:10px;padding:11px 14px;font-size:14.5px}
        /* All four edges in the box's own colour at deliberately UNEVEN widths: the heavy bottom + trailing
           pair reads as a drop shadow, the light top + leading pair closes the outline. Keep the widths
           distinct (4.5px is intended — it is exact on HiDPI). Logical edges, not left/right, so the shadow
           lands on the trailing side of the RTL page with no [dir=rtl] override. */
        .note.tip{background:rgba(61,64,91,.055);border-bottom:7px solid var(--navy,#3D405B);border-inline-end:4.5px solid var(--navy,#3D405B);border-top:2px solid var(--navy,#3D405B);border-inline-start:2px solid var(--navy,#3D405B)}
        .note.warn{background:rgba(224,122,95,.11);border-bottom:7px solid var(--accent,#E07A5F);border-inline-end:4.5px solid var(--accent,#E07A5F);border-top:2px solid var(--accent,#E07A5F);border-inline-start:2px solid var(--accent,#E07A5F)}
        figure{margin:16px 0;text-align:center}
        /* The SVG carries its natural width as a cap and shrinks with the column — never blown up past
           the size it was drawn at, which is the same rule the in-app renderer follows. */
        svg.fig{max-width:100%;height:auto;display:block;margin:0 auto}
        figcaption{margin-top:8px;color:var(--muted,#6b6f7d);font-size:13.5px;font-style:italic}

        @media (max-width:900px){
          .helpwrap{grid-template-columns:1fr;gap:0}
          .toc{position:static;max-height:none;padding-bottom:10px;
            border-bottom:1px solid var(--line,#e6e7ec)}
        }

        /* Right-to-left pages: the contents rail's active bar and list indents swap sides; flex rows and
           text alignment mirror on their own. */
        [dir=rtl] .toc a{border-left:0;border-right:2px solid transparent}
        [dir=rtl] .toc a[aria-current]{border-right-color:var(--accent,#E07A5F)}
        [dir=rtl] .topic ul{padding-left:0;padding-right:20px}
        """;

    /// <summary>Logo is root-absolute in the flattened <c>/assets/</c> — there is no <c>assets/radiata/</c>
    /// folder on the site. The language switcher lives in the site nav, not here.</summary>
    private static string Masthead(string code)
    {
        var c = ChromeFor(code);
        var sb = new StringBuilder();
        sb.AppendLine("<header class=\"helphead\"><div class=\"wrap\">");
        sb.AppendLine("  <div class=\"row\">");
        sb.AppendLine("    <img src=\"/assets/flower-mark-color-unique.png\" width=\"44\" height=\"44\" alt=\"\">");
        sb.AppendLine("    <div>");
        sb.AppendLine($"      <h1>{Esc(c.Heading)}</h1>");
        sb.AppendLine($"      <p>{c.Subtitle}</p>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("  <div class=\"searchrow\">");
        sb.AppendLine($"    <input type=\"search\" id=\"q\" autocomplete=\"off\" placeholder=\"{Esc(HelpLocalization.Text(code, HelpLocalization.Chrome.SearchTip))}\" aria-label=\"{Esc(HelpLocalization.Text(code, HelpLocalization.Chrome.SearchTip))}\">");
        sb.AppendLine("  </div>");
        sb.AppendLine("</div></header>");
        return sb.ToString();
    }

    /// <summary>Identical to every other page's footer; the GitHub link is the profile, not the repo.</summary>
    private static string Footer(string code) => $"""
        <footer><div class="wrap"><div class="row">
          <span>&copy; 2026 Jesse Holden</span>
          <span><a href="{SiteHref("", code)}">{Esc(ChromeFor(code).FooterHome)}</a> &middot; <a href="https://github.com/scumbly">GitHub</a></span>
        </div></div></footer>
        """ + "\n";

    /// <summary>Search + reading position. Filtering hides whole topics and their contents entries, which
    /// is what the in-app pane does; with no query everything comes back.</summary>
    private static string Script(string index) => """
        <script>
        (function () {
          // Retired topic ids stay resolvable so published deep links survive a rename.
          var ALIAS = { 'anticheat-safe-mode': 'passthru-mode' };
          function realias() { var h = location.hash.slice(1); if (ALIAS[h]) location.replace('#' + ALIAS[h]); }
          realias();
          window.addEventListener('hashchange', realias);

          var IX = __INDEX__;
          var box = document.getElementById('q');
          var arts = document.querySelectorAll('.topic');
          var rows = document.querySelectorAll('.toc li');
          var none = document.querySelector('.nomatch');
          var byId = {};
          IX.forEach(function (e) { byId[e.id] = e.t; });

          function show(id, on) {
            var a = document.getElementById(id); if (a) a.hidden = !on;
            var r = document.querySelector('.toc li[data-topic="' + id + '"]'); if (r) r.hidden = !on;
          }
          function filter() {
            var terms = box.value.toLowerCase().split(/\s+/).filter(Boolean);
            var hits = 0;
            IX.forEach(function (e) {
              var ok = terms.every(function (t) { return e.t.indexOf(t) >= 0; });
              if (ok) hits++;
              show(e.id, ok);
            });
            none.hidden = hits > 0;
          }
          box.addEventListener('input', filter);

          // Mark the contents entry for whatever is being read. rootMargin pins the "current" band near
          // the top of the viewport, so the highlight tracks the heading you are actually looking at.
          if ('IntersectionObserver' in window) {
            var seen = {};
            var io = new IntersectionObserver(function (es) {
              es.forEach(function (e) { seen[e.target.id] = e.isIntersecting; });
              var cur = null;
              arts.forEach(function (a) { if (!cur && seen[a.id]) cur = a.id; });
              rows.forEach(function (r) {
                var a = r.querySelector('a');
                if (a) { if (r.dataset.topic === cur) a.setAttribute('aria-current', 'true'); else a.removeAttribute('aria-current'); }
              });
            }, { rootMargin: '-10% 0px -70% 0px' });
            arts.forEach(function (a) { io.observe(a); });
          }
        })();
        </script>
        """.Replace("__INDEX__", index) + "\n";
}
