// <auto-generated> RADIATA PICKER — do not hand-edit. Regenerate with
// `Radiata.exe --export-picker`, then copy %APPDATA%\Radiata\CuratedArt.g.cs over this file.
// Data: curated Radiata Picker choices, pinned as explicit SteamGridDB URLs. </auto-generated>
namespace ControllerWheel;

internal static partial class CuratedArt
{
    private static readonly Dictionary<string, Entry> Table = new(StringComparer.Ordinal)
    {
        // Roblox  (cover: pick, logo: pick, slice: pick)
        ["roblox"] = new("https://cdn2.steamgriddb.com/grid/b730939496ee6181f636e89b03697627.png", null, "https://cdn2.steamgriddb.com/logo/05959582fd11fd858d3280739df2b715.png", false, "https://cdn2.steamgriddb.com/logo/05959582fd11fd858d3280739df2b715.png"),
        // Fortnite  (cover: pick, logo: hidden, slice: pick)
        ["fortnite"] = new("https://cdn2.steamgriddb.com/grid/4944e4ea87bc6821ae44cfbc7821ae26.png", null, null, true, "https://cdn2.steamgriddb.com/logo/c182dc5c90dc87dfee9cd309c33f19b3.png"),
        // League of Legends  (cover: pick, logo: default, slice: default)
        ["leagueoflegends"] = new("https://cdn2.steamgriddb.com/grid/199c79ae66904c729433196aad9ee951.png", null, "https://cdn2.steamgriddb.com/logo/e7bb900e1736ca0d271b420ae968c9da.png", false, "https://cdn2.steamgriddb.com/logo/fa3dade3a49305f27f64203452ac954c.png"),
        // Counter-Strike 2  (cover: pick, logo: default, slice: default)
        ["counterstrike2"] = new("https://cdn2.steamgriddb.com/grid/74d2bd1261cd7590e2acdfa9990b64e5.png", null, "https://cdn2.steamgriddb.com/logo/0b1dd23f1141c0d2a9bfaff1284e0b11.png", false, "https://cdn2.steamgriddb.com/logo/bfe02f81ad5d8d45bb23db5e026e898b.png"),
        // Minecraft  (cover: pick, logo: default, slice: pick)
        ["minecraft"] = new("https://cdn2.steamgriddb.com/grid/0ed5055450adbd836945761a6fa43ee0.jpg", null, "https://cdn2.steamgriddb.com/logo/abcbd2c726f2d695950512f5c6832b6b.png", false, "https://cdn2.steamgriddb.com/logo/90915208c601cc8c86ad01250ee90c12.png"),
        // Dota 2  (cover: pick, logo: hidden, slice: pick)
        ["dota2"] = new("https://cdn2.steamgriddb.com/grid/f7fb771bf04d1d210304db69f6649dfc.png", null, null, true, "https://cdn2.steamgriddb.com/logo/57c29a4600a00164ce8b7f527b6bccc5.png"),
        // Valorant  (cover: pick, logo: default, slice: default)
        ["valorant"] = new("https://cdn2.steamgriddb.com/grid/58d68bcc829b2abb88f8fc1e035a9dc3.png", null, "https://cdn2.steamgriddb.com/logo/4572837cfa3489c4ef6c180ff21eb8ca.png", false, "https://cdn2.steamgriddb.com/logo/c5ba4cd6a42c8364c6ff42b91db8d2ac.png"),
        // Call of Duty  (cover: pick, logo: pick, slice: pick)
        ["callofduty"] = new("https://cdn2.steamgriddb.com/grid/abc08456cfdc28e5ae109e8898eabf29.png", null, "https://cdn2.steamgriddb.com/logo/82704fa1c2dbdb928bf4eed0667260dd.png", false, "https://cdn2.steamgriddb.com/logo/82704fa1c2dbdb928bf4eed0667260dd.png"),
        // PUBG: BATTLEGROUNDS  (cover: pick, logo: default, slice: default)
        ["pubgbattlegrounds"] = new("https://cdn2.steamgriddb.com/grid/93e834de5ae9c81bc0e429317ad399c1.png", null, "https://cdn2.steamgriddb.com/logo/72bf4c46f51738b13e2f7a204e39a7ec.png", false, "https://cdn2.steamgriddb.com/logo/83da7c539e1ab4e759623c38d8737e9e.png"),
        // Palworld  (cover: pick, logo: default, slice: pick)
        ["palworld"] = new("https://cdn2.steamgriddb.com/grid/d0c2b1e87b18968832aec662ff2889dd.png", null, "https://cdn2.steamgriddb.com/logo/1accdd0ee4cf7775f311ee228d73d074.png", false, "https://cdn2.steamgriddb.com/logo/849f1e4d940d9fa0190e224c078bf445.png"),
        // Grand Theft Auto V  (cover: pick, logo: hidden, slice: default)
        ["grandtheftautov"] = new("https://cdn2.steamgriddb.com/grid/e68aea589393df47d1ffb43dcdbdff49.png", null, null, true, "https://cdn2.steamgriddb.com/logo/e5b294b70c9647dcf804d7baa1903918.png"),
        // EA SPORTS FC 26  (cover: pick, logo: hidden, slice: default)
        ["easportsfc26"] = new("https://cdn2.steamgriddb.com/grid/a04a39d5fa3da4a460733733da9f2258.png", null, null, true, "https://cdn2.steamgriddb.com/logo/482e1b522a4cffcac16b67510ee64a2f.png"),
        // Apex Legends  (cover: pick, logo: hidden, slice: default)
        ["apexlegends"] = new("https://cdn2.steamgriddb.com/grid/ad016a70960849e9ee1e6a286bbba410.png", null, null, true, "https://cdn2.steamgriddb.com/logo/21f0db5872591cdad329f08cd5a1f770.png"),
        // Rust  (cover: pick, logo: pick, slice: pick)
        ["rust"] = new("https://cdn2.steamgriddb.com/grid/22c9fb3c8efd34dfb32c8cbf21ffb3d5.png", null, "https://cdn2.steamgriddb.com/logo/620bde855d806c199c826760aa4dc009.png", false, "https://cdn2.steamgriddb.com/logo/620bde855d806c199c826760aa4dc009.png"),
        // Path of Exile  (cover: pick, logo: default, slice: pick)
        ["pathofexile"] = new("https://cdn2.steamgriddb.com/grid/f6f0655687b41bca41c7cb54c5d407ba.png", null, "https://cdn2.steamgriddb.com/logo/0c945a8e12dd7ff713c275c1ad6de9e1.png", false, "https://cdn2.steamgriddb.com/logo/ab49ef78e2877bfd2c2bfa738e459bf0.png"),
        // Marvel Rivals  (cover: pick, logo: pick, slice: default)
        ["marvelrivals"] = new("https://cdn2.steamgriddb.com/grid/72a46ee6c3f5308603f41deb7ba5e35c.png", null, "https://cdn2.steamgriddb.com/logo/2053a19840bca72e34d6fe3781421d94.png", false, "https://cdn2.steamgriddb.com/logo/2053a19840bca72e34d6fe3781421d94.png"),
        // The Sims 4  (cover: pick, logo: default, slice: default)
        ["thesims4"] = new("https://cdn2.steamgriddb.com/grid/c5d566ec3c2d5e81193cec5703b0c71c.png", null, "https://cdn2.steamgriddb.com/logo/cfb8d2b839c4453d97b99a83e54a0e7b.png", false, "https://cdn2.steamgriddb.com/logo/b427426b8acd2c2e53827970f2c2f526.png"),
        // Tom Clancy’s Rainbow Six Siege  (cover: default, logo: default, slice: default)
        ["tomclancysrainbowsixsiege"] = new("https://cdn2.steamgriddb.com/grid/c32d0e02132a853fdf5b8010aa71602e.png", null, "https://cdn2.steamgriddb.com/logo/ea5a312ad646a5d8927093ffe87ed3c6.png", false, "https://cdn2.steamgriddb.com/logo/69961657077e0093ed761aa01916c5ff.png"),
        // Dead by Daylight  (cover: pick, logo: hidden, slice: default)
        ["deadbydaylight"] = new("https://cdn2.steamgriddb.com/grid/0e346d36ba09197dc912a4021c346a53.png", null, null, true, "https://cdn2.steamgriddb.com/logo/230412c7a68201e0be2f5d4fb9d442b4.png"),
        // Warframe  (cover: default, logo: default, slice: default)
        ["warframe"] = new("https://cdn2.steamgriddb.com/grid/f8994ad509ce1a4c46a23fda2a94ada4.jpg", null, "https://cdn2.steamgriddb.com/logo/94512b6faed84f03d6a7e8e561fa6096.png", false, "https://cdn2.steamgriddb.com/logo/7dcf06698a343e7d4985689898cb8491.png"),
        // Battlefield 6  (cover: default, logo: default, slice: pick)
        ["battlefield6"] = new("https://cdn2.steamgriddb.com/grid/057f1b7fff0ae3484684fdda24c04d08.png", null, "https://cdn2.steamgriddb.com/logo/5e932e162654dd96ff5876214dbee53a.png", false, "https://cdn2.steamgriddb.com/logo/2ea46606d79961cff409a5af4d64a8bc.png"),
        // Overwatch 2  (cover: pick, logo: pick, slice: default)
        ["overwatch2"] = new("https://cdn2.steamgriddb.com/grid/f8013fd6d898ca4374d8113f0939c70c.png", null, "https://cdn2.steamgriddb.com/logo/4deedd8d0627e5b5beb4bd0f9b9e3f39.png", false, "https://cdn2.steamgriddb.com/logo/c81e728d9d4c2f636f067f89cc14862c.png"),
        // Escape from Tarkov  (cover: pick, logo: default, slice: default)
        ["escapefromtarkov"] = new("https://cdn2.steamgriddb.com/grid/7aeb4e2cc65d4f290848f9699810c4f0.png", null, "https://cdn2.steamgriddb.com/logo/b2531e7bb29bf22e1daae486fae3417a.png", false, "https://cdn2.steamgriddb.com/logo/b2531e7bb29bf22e1daae486fae3417a.png"),
        // World of Warcraft  (cover: pick, logo: default, slice: default)
        ["worldofwarcraft"] = new("https://cdn2.steamgriddb.com/grid/c8fcd3fb8ac2645797d096c8993e066c.png", null, "https://cdn2.steamgriddb.com/logo/c90070e1f03e982448983975a0f52d57.png", false, "https://cdn2.steamgriddb.com/logo/5236d2d466e7a1d9785a33e298a58c3c.png"),
        // Diablo IV  (cover: pick, logo: default, slice: default)
        ["diabloiv"] = new("https://cdn2.steamgriddb.com/grid/633ae77e46b449277ec221641014c17d.jpg", null, "https://cdn2.steamgriddb.com/logo/666b9ed0739d8d309d3a72e199026072.png", false, "https://cdn2.steamgriddb.com/logo/94e19ae9b74d13ad42e20407ffe4d95d.png"),
        // Rocket League  (cover: pick, logo: pick, slice: pick)
        ["rocketleague"] = new("https://cdn2.steamgriddb.com/grid/e4e4005042cf598805d581754fe9256f.png", null, "https://cdn2.steamgriddb.com/logo/350e66193d449030fa9f25844b37986d.png", false, "https://cdn2.steamgriddb.com/logo/350e66193d449030fa9f25844b37986d.png"),
        // Final Fantasy XIV Online  (cover: pick, logo: default, slice: pick)
        ["finalfantasyxivonline"] = new("https://cdn2.steamgriddb.com/grid/0f0daf20cf5762ce062c08441286d72d.png", null, "https://cdn2.steamgriddb.com/logo/85ed80330988fd5fc9cd44b6efc379e6.png", false, "https://cdn2.steamgriddb.com/logo/46fc943ecd56441056a560ba37d0b9e8.png"),
        // Black Desert  (cover: pick, logo: pick, slice: default)
        ["blackdesert"] = new("https://cdn2.steamgriddb.com/grid/d1646142b183e4418a49e78a5ebd7d0f.png", null, "https://cdn2.steamgriddb.com/logo/8c0b24e61de5e3a439564c221adb6e89.png", false, "https://cdn2.steamgriddb.com/logo/b136f93c7eae6130e704ec78b945d5c6.png"),
        // Old School RuneScape  (cover: pick, logo: default, slice: default)
        ["oldschoolrunescape"] = new("https://cdn2.steamgriddb.com/grid/bb597418495f220395192db2d22d6e27.png", null, "https://cdn2.steamgriddb.com/logo/ce4289582a65bb7fd0432f697bb08d97.png", false, "https://cdn2.steamgriddb.com/logo/a39878ae282a18ea051ad89e7875a272.png"),
        // Genshin Impact  (cover: pick, logo: default, slice: default)
        ["genshinimpact"] = new("https://cdn2.steamgriddb.com/grid/8d6e71df690e725cd44191006dac31da.png", null, "https://cdn2.steamgriddb.com/logo/fd278a8f5571d3db556bd83198beb09a.png", false, "https://cdn2.steamgriddb.com/logo/944eefd22dfe99fe7631b8ecc732c7cf.png"),
        // Delta Force  (cover: flat, logo: default, slice: pick)
        ["deltaforce"] = new(null, "000000", "https://cdn2.steamgriddb.com/logo/ffb8cd4c0d6dc980350a747a716859f7.png", false, "https://cdn2.steamgriddb.com/logo/48e770a9e95213cab24019b4604c3dca.png"),
        // Path of Exile 2  (cover: pick, logo: default, slice: pick)
        ["pathofexile2"] = new("https://cdn2.steamgriddb.com/grid/602dc7261c04c9ae1d85e4ef3d191f0a.png", null, "https://cdn2.steamgriddb.com/logo/c74db16a09102912b8a4dd9c8dd1b581.png", false, "https://cdn2.steamgriddb.com/logo/a24f26d8f3b52333c019fae80ccac40d.png"),
        // Destiny 2  (cover: pick, logo: hidden, slice: pick)
        ["destiny2"] = new("https://cdn2.steamgriddb.com/grid/20e64ecc8467f72baa3ba3adbaa4fa0f.png", null, null, true, "https://cdn2.steamgriddb.com/logo/7cfc37ec1434434ea9e2c926984fd996.png"),
        // Project Zomboid  (cover: pick, logo: default, slice: default)
        ["projectzomboid"] = new("https://cdn2.steamgriddb.com/grid/95d8125601dd6fea147e48f1dcca595e.png", null, "https://cdn2.steamgriddb.com/logo/074ab924540667aad42a8ea3beccd19b.png", false, "https://cdn2.steamgriddb.com/logo/074ab924540667aad42a8ea3beccd19b.png"),
        // Stardew Valley  (cover: pick, logo: pick, slice: pick)
        ["stardewvalley"] = new("https://cdn2.steamgriddb.com/grid/19e2a40db4e1365c35a66e97de3783a5.png", null, "https://cdn2.steamgriddb.com/logo/a15612aee1f0b2fdf1768df0d2688bd1.png", false, "https://cdn2.steamgriddb.com/logo/c9079272e7ee76e97719613b234763c2.png"),
        // War Thunder  (cover: default, logo: default, slice: default)
        ["warthunder"] = new("https://cdn2.steamgriddb.com/grid/76a099847cba84bdbb61d96a9d06668b.jpg", null, "https://cdn2.steamgriddb.com/logo/4927e1395ab1d386386a762cad17d7a7.png", false, "https://cdn2.steamgriddb.com/logo/54d22f8632eb479849f7bad14f024ce5.png"),
        // Team Fortress 2  (cover: pick, logo: pick, slice: default)
        ["teamfortress2"] = new("https://cdn2.steamgriddb.com/grid/c2ceb44e794fc91f1cdf4027008f0807.png", null, "https://cdn2.steamgriddb.com/logo/44b4596c7a979aa7e4fc820c07fd78fe.png", false, "https://cdn2.steamgriddb.com/logo/49490f256a90aff2c2c4e151515fe241.png"),
        // Slay the Spire 2  (cover: pick, logo: hidden, slice: default)
        ["slaythespire2"] = new("https://cdn2.steamgriddb.com/grid/e65fabf4c175f1c4294ecbe64d072471.png", null, null, true, "https://cdn2.steamgriddb.com/logo/810f048aa6adcc95c64dca23ef9883f6.png"),
        // Baldur’s Gate 3  (cover: pick, logo: hidden, slice: default)
        ["baldursgate3"] = new("https://cdn2.steamgriddb.com/grid/3240194f5e06d830eece42653b01ee21.png", null, null, true, "https://cdn2.steamgriddb.com/logo/71d9945703c17fafe19f7dd1c706d448.png"),
        // Cyberpunk 2077  (cover: pick, logo: default, slice: pick)
        ["cyberpunk2077"] = new("https://cdn2.steamgriddb.com/grid/f39b781760a403dedaa05587e8889c1a.png", null, "https://cdn2.steamgriddb.com/logo/91d8c479ac8f6ca2291cd95a31c46b31.png", false, "https://cdn2.steamgriddb.com/logo/2b2e7393b05b5b52af65bf2ed7f4ad4f.png"),
        // DayZ  (cover: pick, logo: hidden, slice: default)
        ["dayz"] = new("https://cdn2.steamgriddb.com/grid/f9d57d342163476ec8ad7c4ef1491f0b.png", null, null, true, "https://cdn2.steamgriddb.com/logo/686684686c10fb28b76058e75c6978e2.png"),
        // VRChat  (cover: pick, logo: default, slice: default)
        ["vrchat"] = new("https://cdn2.steamgriddb.com/grid/36deb46b8a06e33e4c96036ff9bdabd0.png", null, "https://cdn2.steamgriddb.com/logo/e0cd3f16f9e883ca91c2a4c24f47b3d9.png", false, "https://cdn2.steamgriddb.com/logo/dd409260aea46a90e61b9a69fb9726ef.png"),
        // BeamNG.drive  (cover: pick, logo: hidden, slice: default)
        ["beamngdrive"] = new("https://cdn2.steamgriddb.com/grid/9c267a4b6f353b24aff1ed3966a7ddba.png", null, null, true, "https://cdn2.steamgriddb.com/logo/f06e359e69c17ae035e7d1559e50c5d1.png"),
        // Hearts of Iron IV  (cover: pick, logo: default, slice: default)
        ["heartsofironiv"] = new("https://cdn2.steamgriddb.com/grid/b82c662168a672cb8f9b7695bb1e3842.png", null, "https://cdn2.steamgriddb.com/logo/e49bd9455e01925fe6cf5ea50bd793d2.png", false, "https://cdn2.steamgriddb.com/logo/93eb9cfb64391c4ee20ac49e72216fa4.png"),
        // Football Manager 26  (cover: pick, logo: hidden, slice: default)
        ["footballmanager26"] = new("https://cdn2.steamgriddb.com/grid/e483e8099e0620eef37de9aab6613393.jpg", null, null, true, "https://cdn2.steamgriddb.com/logo/25a572e2727e193711d91374f4da099f.png"),
        // Euro Truck Simulator 2  (cover: default, logo: default, slice: default)
        ["eurotrucksimulator2"] = new("https://cdn2.steamgriddb.com/grid/2b8839b81684f6649afbd26646ec5cd5.png", null, "https://cdn2.steamgriddb.com/logo/4b280c37f5d6adde95399691bcd03ccf.png", false, "https://cdn2.steamgriddb.com/logo/69119d4f2670e411071c9cb8d7d01b27.png"),
        // Farming Simulator 25  (cover: pick, logo: hidden, slice: default)
        ["farmingsimulator25"] = new("https://cdn2.steamgriddb.com/grid/8c7d367ddd4bc66ce6aba1f76235b0bf.png", null, null, true, "https://cdn2.steamgriddb.com/logo/8e30429e45ca0c6376613084d7dbaffd.png"),
        // Arena Breakout: Infinite  (cover: pick, logo: hidden, slice: default)
        ["arenabreakoutinfinite"] = new("https://cdn2.steamgriddb.com/grid/011c87f62967da0a377677c8a716fd2b.png", null, null, true, "https://cdn2.steamgriddb.com/logo/f9e847af5e5875b5387298ec7fb36bf0.png"),
        // Garry’s Mod  (cover: pick, logo: hidden, slice: pick)
        ["garrysmod"] = new("https://cdn2.steamgriddb.com/grid/a2a9894ca446f0fe0aac693516c52c4d.png", null, null, true, "https://cdn2.steamgriddb.com/logo/e065cfbe04875966d6711e857e42741c.png"),
        // ARC Raiders  (cover: pick, logo: hidden, slice: default)
        ["arcraiders"] = new("https://cdn2.steamgriddb.com/grid/91dad5ea2a259ff89e74149596caef9b.png", null, null, true, "https://cdn2.steamgriddb.com/logo/f6cba8ff9ff660c6658331395bb5ae34.png"),
        // Red Dead Redemption 2  (cover: pick, logo: hidden, slice: default)
        ["reddeadredemption2"] = new("https://cdn2.steamgriddb.com/grid/414993dd850f6af49b3c51a26206aca3.png", null, null, true, "https://cdn2.steamgriddb.com/logo/ff38348a5adb1889dd55c7ccba583c43.png"),
        // Terraria  (cover: pick, logo: default, slice: default)
        ["terraria"] = new("https://cdn2.steamgriddb.com/grid/9ef7f9b81c2532880cfe5cf53f0c906d.png", null, "https://cdn2.steamgriddb.com/logo/6b60d49b35c6a9a0136aea9e9276fd6f.png", false, "https://cdn2.steamgriddb.com/logo/af922fd52975aee0083fb8e0ba9c1d64.png"),
        // Elden Ring  (cover: pick, logo: default, slice: pick)
        ["eldenring"] = new("https://cdn2.steamgriddb.com/grid/a0abf0396a718b8982fce0b80181d8cb.png", null, "https://cdn2.steamgriddb.com/logo/8ed67538022400bdba14f3e8b4bf6ab3.png", false, "https://cdn2.steamgriddb.com/logo/6076036fdb272f49688c571013f3ede1.png"),
        // RimWorld  (cover: pick, logo: default, slice: pick)
        ["rimworld"] = new("https://cdn2.steamgriddb.com/grid/025482093f50e113ff4a3e6ab33c7e54.png", null, "https://cdn2.steamgriddb.com/logo/de06ce4800bd5a95f4dc7312700c3e3e.png", false, "https://cdn2.steamgriddb.com/logo/5d512a3304dc67b23a010a05ef1398a4.png"),
        // The Elder Scrolls V: Skyrim Special Edition  (cover: pick, logo: hidden, slice: default)
        ["theelderscrollsvskyrimspecialedition"] = new("https://cdn2.steamgriddb.com/grid/7515b9ccd735266ed14ff0b45fd76cf6.png", null, null, true, "https://cdn2.steamgriddb.com/logo/2e2079d63348233d91cad1fa9b1361e9.png"),
        // ARK: Survival Ascended  (cover: pick, logo: hidden, slice: default)
        ["arksurvivalascended"] = new("https://cdn2.steamgriddb.com/grid/605205339043a22a016f0e7b6b87e207.png", null, null, true, "https://cdn2.steamgriddb.com/logo/49616ab5001dd01538f33c56818f9478.png"),
        // HELLDIVERS 2  (cover: pick, logo: pick, slice: default)
        ["helldivers2"] = new("https://cdn2.steamgriddb.com/grid/f097cfbb02280b31c19982d9e56e7bb5.png", null, "https://cdn2.steamgriddb.com/logo/c469a6d123d89869a33da175b9c9a5e3.png", false, "https://cdn2.steamgriddb.com/logo/0abe10cc20cfedb109fd9cee834adc18.png"),
        // Mount & Blade II: Bannerlord  (cover: default, logo: default, slice: default)
        ["mountbladeiibannerlord"] = new("https://cdn2.steamgriddb.com/grid/d6f8867257901d6e9b0ac8b05c196873.png", null, "https://cdn2.steamgriddb.com/logo/e43a09ffc30b44cb1f0db46f87836f40.png", false, "https://cdn2.steamgriddb.com/logo/f88f8f0d9f5d571b38a7914b74f63a9e.png"),
        // Total War: WARHAMMER III  (cover: pick, logo: default, slice: default)
        ["totalwarwarhammeriii"] = new("https://cdn2.steamgriddb.com/grid/f0ef376bcffed379553591385cf4dc21.png", null, "https://cdn2.steamgriddb.com/logo/d5d5754b7f029ea69190cee5ea20cfce.png", false, "https://cdn2.steamgriddb.com/logo/ef5b0acc4a9fef53a0b84fea9ea01c69.png"),
        // Left 4 Dead 2  (cover: default, logo: pick, slice: default)
        ["left4dead2"] = new("https://cdn2.steamgriddb.com/grid/281295a1f0e200cd7dc417d82bb4b045.jpg", null, "https://cdn2.steamgriddb.com/logo/8549c938065011dc634e597bacb611de.png", false, "https://cdn2.steamgriddb.com/logo/8549c938065011dc634e597bacb611de.png"),
        // Forza Horizon 6  (cover: pick, logo: pick, slice: default)
        ["forzahorizon6"] = new("https://cdn2.steamgriddb.com/grid/cd98f0e279d66f4d9acf0e3df40be97a.png", null, "https://cdn2.steamgriddb.com/logo/2c618774f88d9b2a617f9683b6a6ee5c.png", false, "https://cdn2.steamgriddb.com/logo/e16ac684c3fbf507cfbbf4e37bf19feb.png"),
        // NARAKA: BLADEPOINT  (cover: default, logo: default, slice: default)
        ["narakabladepoint"] = new("https://cdn2.steamgriddb.com/grid/8030eb90204f9b7e85e0eed6ea33722e.png", null, "https://cdn2.steamgriddb.com/logo/733bf40648f654e2a0f367c8cb16856a.png", false, "https://cdn2.steamgriddb.com/logo/733bf40648f654e2a0f367c8cb16856a.png"),
        // Don’t Starve Together  (cover: pick, logo: default, slice: pick)
        ["dontstarvetogether"] = new("https://cdn2.steamgriddb.com/grid/d09a3319b837ca2be50b18c294fa2c79.png", null, "https://cdn2.steamgriddb.com/logo/6e56378061ec42edea778394c32755cf.png", false, "https://cdn2.steamgriddb.com/logo/9ae0a504e3af13e2e6b3ff478a8f637b.png"),
        // Zenless Zone Zero  (cover: pick, logo: default, slice: pick)
        ["zenlesszonezero"] = new("https://cdn2.steamgriddb.com/grid/ec67232d98db337b536a51dfc365f359.jpg", null, "https://cdn2.steamgriddb.com/logo/da9f8fa9abca67a47cbc61b5151ee3cf.png", false, "https://cdn2.steamgriddb.com/logo/27a44760b9dc8539adc142291f75296e.png"),
        // Warhammer 40,000: Space Marine 2  (cover: pick, logo: default, slice: default)
        ["warhammer40000spacemarine2"] = new("https://cdn2.steamgriddb.com/grid/6396c8ace492bf07e78ee2d6cc76c275.png", null, "https://cdn2.steamgriddb.com/logo/61d06545a9b5a3c1a8993909f9ca65e5.png", false, "https://cdn2.steamgriddb.com/logo/e8a0ec28fc4273aa546f3abb6a3c24d9.png"),
        // Crusader Kings III  (cover: pick, logo: pick, slice: default)
        ["crusaderkingsiii"] = new("https://cdn2.steamgriddb.com/grid/e71d8e6fd702e874046a5702a1c15acf.png", null, "https://cdn2.steamgriddb.com/logo/5713d94b932fda2d38d15466f4d5d7a1.png", false, "https://cdn2.steamgriddb.com/logo/5713d94b932fda2d38d15466f4d5d7a1.png"),
        // Valheim  (cover: pick, logo: default, slice: default)
        ["valheim"] = new("https://cdn2.steamgriddb.com/grid/15bae9fa92cfa7982d794811b05162c9.png", null, "https://cdn2.steamgriddb.com/logo/70e12d315a19ad3e37b2593a58f37459.png", false, "https://cdn2.steamgriddb.com/logo/d00f448c26753a69f75336c46e974848.png"),
        // Satisfactory  (cover: pick, logo: pick, slice: pick)
        ["satisfactory"] = new("https://cdn2.steamgriddb.com/grid/960022abd82d76dab840c7943826fd3a.png", null, "https://cdn2.steamgriddb.com/logo/36cc76f6dc57f50bdbda82f92aff1b94.png", false, "https://cdn2.steamgriddb.com/logo/36cc76f6dc57f50bdbda82f92aff1b94.png"),
        // Factorio  (cover: pick, logo: default, slice: pick)
        ["factorio"] = new("https://cdn2.steamgriddb.com/grid/0ded6348389f35483e961d04d7babcc8.png", null, "https://cdn2.steamgriddb.com/logo/68e5585094320268d22a83399be4ca8d.png", false, "https://cdn2.steamgriddb.com/logo/674bfc5f6b72706fb769f5e93667bd23.png"),
        // Hunt: Showdown 1896  (cover: pick, logo: hidden, slice: default)
        ["huntshowdown1896"] = new("https://cdn2.steamgriddb.com/grid/fbc9b51da15391491dfead2ce7830a00.png", null, null, true, "https://cdn2.steamgriddb.com/logo/c63617a9a72525823735487489f14ac5.png"),
        // ARK: Survival Evolved  (cover: pick, logo: hidden, slice: pick)
        ["arksurvivalevolved"] = new("https://cdn2.steamgriddb.com/grid/190e544f8382a0b1090ecbe3ddf8422a.png", null, null, true, "https://cdn2.steamgriddb.com/logo/ca43108ded5aabc7793d3f9b928cdd54.png"),
        // The Witcher 3: Wild Hunt  (cover: pick, logo: default, slice: default)
        ["thewitcher3wildhunt"] = new("https://cdn2.steamgriddb.com/grid/c5d76cca317966602bb28a668a2c4cd8.png", null, "https://cdn2.steamgriddb.com/logo/053e9646748ec85c2e1424402bf9419f.png", false, "https://cdn2.steamgriddb.com/logo/be37636fec7514e291c13c1024c56a9b.png"),
        // Age of Empires II: Definitive Edition  (cover: default, logo: default, slice: default)
        ["ageofempiresiidefinitiveedition"] = new("https://cdn2.steamgriddb.com/grid/6c17d0d1ddf13851c59bf49b1b0e5bee.png", null, "https://cdn2.steamgriddb.com/logo/757f843a169cc678064d9530d12a1881.png", false, "https://cdn2.steamgriddb.com/logo/757f843a169cc678064d9530d12a1881.png"),
        // NBA 2K26  (cover: pick, logo: hidden, slice: pick)
        ["nba2k26"] = new("https://cdn2.steamgriddb.com/grid/f0755e4cc476676dd435bc2859df0680.png", null, null, true, "https://cdn2.steamgriddb.com/logo/8c3baa8d5e033d483637b0d0dada9d1b.png"),
        // Where Winds Meet  (cover: pick, logo: default, slice: default)
        ["wherewindsmeet"] = new("https://cdn2.steamgriddb.com/grid/84152b968d1b286624f53aa0fa441396.png", null, "https://cdn2.steamgriddb.com/logo/94d1c34dde7de6a269087f167290b48b.png", false, "https://cdn2.steamgriddb.com/logo/c316577b3359b5828141f3677e965fc2.png"),
        // Arma Reforger  (cover: pick, logo: hidden, slice: pick)
        ["armareforger"] = new("https://cdn2.steamgriddb.com/grid/20f3513e0a45de72be6afbe972a5a72a.png", null, null, true, "https://cdn2.steamgriddb.com/logo/46fcc3c13b91db131389c51d90281b02.png"),
        // THE FINALS  (cover: pick, logo: hidden, slice: default)
        ["thefinals"] = new("https://cdn2.steamgriddb.com/grid/a220b18f7302ecd6c80092293dec3138.png", null, null, true, "https://cdn2.steamgriddb.com/logo/e7f6861ecd2f6c7ea51ca6bcc1c54b05.png"),
        // Kingdom Come: Deliverance II  (cover: pick, logo: hidden, slice: default)
        ["kingdomcomedeliveranceii"] = new("https://cdn2.steamgriddb.com/grid/6f8249869e5bdcbbabb0a0bea4acac1e.png", null, null, true, "https://cdn2.steamgriddb.com/logo/a2398594505e26c891e3eac3da80e7fd.png"),
        // EVE Online  (cover: default, logo: default, slice: default)
        ["eveonline"] = new("https://cdn2.steamgriddb.com/grid/620bde855d806c199c826760aa4dc009.png", null, "https://cdn2.steamgriddb.com/logo/527490f08486bf8af2b8d0bf6e73911b.png", false, "https://cdn2.steamgriddb.com/logo/527490f08486bf8af2b8d0bf6e73911b.png"),
        // Guild Wars 2  (cover: default, logo: default, slice: pick)
        ["guildwars2"] = new("https://cdn2.steamgriddb.com/grid/bba9394daa8c273105960cfedd1d51d9.png", null, "https://cdn2.steamgriddb.com/logo/58aedfa8090b3bd19179bda8615a2690.png", false, "https://cdn2.steamgriddb.com/logo/617c81b47e4758942128b6bd2319d9c1.png"),
        // The Elder Scrolls Online  (cover: pick, logo: default, slice: pick)
        ["theelderscrollsonline"] = new("https://cdn2.steamgriddb.com/grid/6b9d57108faa47dd1aa0430dafc443ee.jpg", null, "https://cdn2.steamgriddb.com/logo/26f0714fb58aade4a66a5a5f9cb16b14.png", false, "https://cdn2.steamgriddb.com/logo/08048a9c5630ccb67789a198f35d30ec.png"),
        // Lost Ark  (cover: default, logo: default, slice: default)
        ["lostark"] = new("https://cdn2.steamgriddb.com/grid/16d1463e014629c4db37dfbc739a1cfc.png", null, "https://cdn2.steamgriddb.com/logo/9243749d363441134ab195b4febe391c.png", false, "https://cdn2.steamgriddb.com/logo/9243749d363441134ab195b4febe391c.png"),
        // Monster Hunter Wilds  (cover: pick, logo: hidden, slice: pick)
        ["monsterhunterwilds"] = new("https://cdn2.steamgriddb.com/grid/022f1a0bb8523a8e0d9d8afa86dffc2d.png", null, null, true, "https://cdn2.steamgriddb.com/logo/af1c200b37867473a824e7c94e98d4ec.png"),
        // Monster Hunter: World  (cover: pick, logo: pick, slice: default)
        ["monsterhunterworld"] = new("https://cdn2.steamgriddb.com/grid/d3840924fe89aac052842c1b5268960d.png", null, "https://cdn2.steamgriddb.com/logo/789c5cf0a5d1b4e405320c592b24ee88.png", false, "https://cdn2.steamgriddb.com/logo/789c5cf0a5d1b4e405320c592b24ee88.png"),
        // Wuthering Waves  (cover: default, logo: pick, slice: default)
        ["wutheringwaves"] = new("https://cdn2.steamgriddb.com/grid/6e9c9806cb2287ebdb5c3927a8a0054e.png", null, "https://cdn2.steamgriddb.com/logo/5a72d3dd60aafdf40c6a49dc4948a065.png", false, "https://cdn2.steamgriddb.com/logo/4e0889bb750a24cc76c976b032b78f05.png"),
        // Magic: The Gathering Arena  (cover: default, logo: default, slice: pick)
        ["magicthegatheringarena"] = new("https://cdn2.steamgriddb.com/grid/c416836ac2c2f1c4347126da12784695.png", null, "https://cdn2.steamgriddb.com/logo/ed277964a8959e72a0d987e598dfbe72.png", false, "https://cdn2.steamgriddb.com/logo/ce89f6b11bdc5b365085a84036e9365b.png"),
        // No Man’s Sky  (cover: pick, logo: hidden, slice: default)
        ["nomanssky"] = new("https://cdn2.steamgriddb.com/grid/f1023abc4f90b7cdc6bb1b412864e972.png", null, null, true, "https://cdn2.steamgriddb.com/logo/c61085b95025e125ca4ef45f74c5f537.png"),
        // Sid Meier’s Civilization VI  (cover: pick, logo: pick, slice: default)
        ["sidmeierscivilizationvi"] = new("https://cdn2.steamgriddb.com/grid/7ce9d67d85410c4531d26ee12e9640d2.png", null, "https://cdn2.steamgriddb.com/logo/961f1e759d4e9cca6754b1477b3b491a.png", false, "https://cdn2.steamgriddb.com/logo/f23fde6495582b36958b1e5f6a984ec7.png"),
        // Sid Meier’s Civilization VII  (cover: pick, logo: hidden, slice: pick)
        ["sidmeierscivilizationvii"] = new("https://cdn2.steamgriddb.com/grid/fb2158a06f3118574e63f4d8da6e9a85.png", null, null, true, "https://cdn2.steamgriddb.com/logo/34ad4dfb2edd5ad3828a778d2a5dbb15.png"),
        // Fallout 76  (cover: pick, logo: default, slice: default)
        ["fallout76"] = new("https://cdn2.steamgriddb.com/grid/1aadf27ccf22ef0f59180e0a11f5b223.png", null, "https://cdn2.steamgriddb.com/logo/3795d3a1bcd79ee934bf8ae37c031191.png", false, "https://cdn2.steamgriddb.com/logo/b5488aeff42889188d03c9895255cecc.png"),
        // Dark and Darker  (cover: default, logo: pick, slice: default)
        ["darkanddarker"] = new("https://cdn2.steamgriddb.com/grid/d345cbaa9c2f47902f98bd848afb977c.png", null, "https://cdn2.steamgriddb.com/logo/07871dee9f66217cb9115dfe18355541.png", false, "https://cdn2.steamgriddb.com/logo/9f4daa9161444515136a7907f77a2acd.png"),
        // Albion Online  (cover: default, logo: default, slice: pick)
        ["albiononline"] = new("https://cdn2.steamgriddb.com/grid/51379a25216be592d55dfd1acf510af8.png", null, "https://cdn2.steamgriddb.com/logo/d82dcce748db2b286c31075d899273b0.png", false, "https://cdn2.steamgriddb.com/logo/ecd812da02543c0269cfc2c56ab3c3c0.png"),
        // MapleStory  (cover: pick, logo: pick, slice: pick)
        ["maplestory"] = new("https://cdn2.steamgriddb.com/grid/cb3a230b6ea829971b1344eff6fcec54.png", null, "https://cdn2.steamgriddb.com/logo/1042ee016ad60422f90a4a82ddd9fa40.png", false, "https://cdn2.steamgriddb.com/logo/1042ee016ad60422f90a4a82ddd9fa40.png"),
        // Yu-Gi-Oh! Master Duel  (cover: pick, logo: hidden, slice: default)
        ["yugiohmasterduel"] = new("https://cdn2.steamgriddb.com/grid/97ebd559ac1952c101dd6ac67fdbf587.png", null, null, true, "https://cdn2.steamgriddb.com/logo/35eac895365eb23f12f6d93cf1efc340.png"),
        // Brawlhalla  (cover: pick, logo: default, slice: default)
        ["brawlhalla"] = new("https://cdn2.steamgriddb.com/grid/820b5138a91b4a3ef9a7024cbbcc9af9.png", null, "https://cdn2.steamgriddb.com/logo/186908a1f2edf1e054b8c9fb59c08058.png", false, "https://cdn2.steamgriddb.com/logo/d436cae949c81b9970593a225df2d479.png"),
        // World of Tanks  (cover: pick, logo: pick, slice: pick)
        ["worldoftanks"] = new("https://cdn2.steamgriddb.com/grid/d01d1ca662d5257010298baa3936153e.png", null, "https://cdn2.steamgriddb.com/logo/323817dbbe1a5cca5c571b3bd9fe1bf3.png", false, "https://cdn2.steamgriddb.com/logo/323817dbbe1a5cca5c571b3bd9fe1bf3.png"),
        // World of Warships  (cover: pick, logo: default, slice: default)
        ["worldofwarships"] = new("https://cdn2.steamgriddb.com/grid/c1d92db5defcec11e2551eaad6fbba38.jpg", null, "https://cdn2.steamgriddb.com/logo/617ee761bc8d95fbca3e087602504ebd.png", false, "https://cdn2.steamgriddb.com/logo/68da88f6136bd6e456811e4a1f941ac0.png"),
        // Among Us  (cover: pick, logo: pick, slice: default)
        ["amongus"] = new("https://cdn2.steamgriddb.com/grid/42acab51cf2973d1b174ec59f11c9795.png", null, "https://cdn2.steamgriddb.com/logo/9fa0bb67ba754c1b4e5921c3bc837ceb.png", false, "https://cdn2.steamgriddb.com/logo/9fa0bb67ba754c1b4e5921c3bc837ceb.png"),
        // Phasmophobia  (cover: default, logo: default, slice: pick)
        ["phasmophobia"] = new("https://cdn2.steamgriddb.com/grid/b8ee42f6c6733d5db34b17a5aaa5844d.png", null, "https://cdn2.steamgriddb.com/logo/530cd267315741da2f57ea61dd741d51.png", false, "https://cdn2.steamgriddb.com/logo/a56ab051ba4706847a3475f0434f1f78.png"),
        // Black Myth: Wukong  (cover: pick, logo: hidden, slice: default)
        ["blackmythwukong"] = new("https://cdn2.steamgriddb.com/grid/d193b688361ffe71e8a18d819eb86d4f.png", null, null, true, "https://cdn2.steamgriddb.com/logo/2cb20cf1015104c145ddd098f482005e.png"),
    };
}
