; Radiata installer definition (Inno Setup 6). Compiled by tools\build-installer.ps1, which passes
; every version define — never hardcode a version here. See docs/INSTALLER.md for the contracts
; this file must keep (AppId permanence, the silent-update switches, uninstall ownership).

; The build script must supply these; a bare ISCC run fails here rather than shipping a 0.0 build.
#ifndef AppVer
  #error AppVer is required (pass /DAppVer=0.13.x via tools\build-installer.ps1)
#endif
#ifndef AppVerNum
  #error AppVerNum is required (pass /DAppVerNum=0.13.x.0)
#endif
#ifndef PayloadDir
  #error PayloadDir is required (pass /DPayloadDir=<staging dir>)
#endif

[Setup]
; NEVER change this GUID. It is the upgrade + uninstall identity; a new GUID makes every future
; release install BESIDE the old one instead of over it.
AppId={{FC9B183F-8F24-4343-82FC-7D8CE9914300}
AppName=Radiata
AppVersion={#AppVer}
; Without this, Inno composes the Apps-list DisplayName as "Radiata version <ver>"; the version
; still shows in Windows' own column via DisplayVersion. Also titles the setup wizard "Setup - Radiata".
AppVerName=Radiata
VersionInfoVersion={#AppVerNum}
AppPublisher=Radiata Project
AppPublisherURL=https://getradiata.app
AppSupportURL=https://github.com/scumbly/radiata
AppUpdatesURL=https://getradiata.app

; Per-user, no UAC: files under the user's profile, registration under HKCU. Elevation happens
; only inside the drivers [Run] entry below, via runas on Radiata.exe itself.
PrivilegesRequired=lowest
DefaultDirName={localappdata}\Programs\Radiata
DisableDirPage=yes
DisableProgramGroupPage=yes

ArchitecturesAllowed=x64os
ArchitecturesInstallIn64BitMode=x64os
MinVersion=10.0

; The in-app updater runs this setup /SILENT /CLOSEAPPLICATIONS /NORESTART /RADIATARELAUNCH=1.
; CloseApplications lets a silent upgrade replace a running tray instance; the relaunch is OUR
; [Run] entry gated on RADIATARELAUNCH (RestartApplications stays off — Radiata does not register
; for Restart Manager restart, so Inno's own mechanism cannot bring the tray back).
CloseApplications=yes
RestartApplications=no

Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Wizard language: the picker always shows (never in a silent update — Inno suppresses it under
; /SILENT regardless of this setting). Don't switch this back to "auto" — its detection can land on
; a non-English default with no dialog and no way to change it.
ShowLanguageDialog=yes
; Wizard artwork + colours mirror the in-app first-run wizard (OnboardingWindow / App.xaml chrome
; palette). BMPs are generated by tools\make-wizard-bmps.ps1 from Assets\flower-mark-color-unique.png
; on UiWindowBg — regenerate them if that asset or the palette changes. The matching
; recolour code lives in InitializeWizard below.
WizardImageFile=assets\radiata-wizard-*.bmp
WizardSmallImageFile=assets\radiata-wizard-small-*.bmp
OutputBaseFilename=Radiata-{#AppVer}-setup
SetupIconFile=..\Assets\radiata.ico
UninstallDisplayIcon={app}\Radiata.exe

; No LicenseFile on purpose: GPL is a distribution license, not an EULA — presenting it as a
; click-through agreement misstates it. The license text is embedded in Radiata.exe and shown from
; Settings > About instead.


[Languages]
; The app's five languages, from Inno's official translations (docs/LOCALIZATION.md §3). Arabic.isl declares
; RightToLeft=yes, so Inno mirrors the wizard itself; the Arabic wizard is an untested surface.
; Every [Messages] override and every user-facing string below carries a per-language form; a bare entry
; would show English inside a Spanish wizard.
Name: "english";  MessagesFile: "compiler:Default.isl"
Name: "spanish";  MessagesFile: "compiler:Languages\Spanish.isl"
Name: "german";   MessagesFile: "compiler:Languages\German.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "arabic";   MessagesFile: "compiler:Languages\Arabic.isl"

[Messages]
; FinishedLabel drops the stock "may be launched by selecting the installed shortcuts" sentence.
; UninstalledMost replaces Inno's "Some elements could not be removed. These can be removed manually.",
; which is wrong for this app's two real cases: a kernel driver mid-removal can only finish via a REBOOT
; (the one remedy the stock text never names), and a briefly AV-held file is deleted by the later passes
; anyway (the failure flag latches on the FIRST failed delete and never clears). Genuine leftovers get
; their own explicit list from usPostUninstall before this message appears.
english.FinishedLabel=Setup has finished installing [name] on your computer.
spanish.FinishedLabel=El programa de instalación ha terminado de instalar [name] en su equipo.
german.FinishedLabel=Das Setup hat die Installation von [name] auf Ihrem Computer abgeschlossen.
japanese.FinishedLabel=セットアップは [name] のインストールを完了しました。
arabic.FinishedLabel=أنهى برنامج الإعداد تثبيت [name] على جهازك.
english.UninstalledMost=Radiata uninstall complete.%n%nWindows will finish some cleanup on its own — if the controller drivers were removed, a restart (now or at your convenience) completes their removal. Nothing needs to be removed manually unless a list of remaining files was just shown.
spanish.UninstalledMost=Desinstalación de Radiata completada.%n%nWindows terminará parte de la limpieza por su cuenta: si se eliminaron los controladores del mando, un reinicio (ahora o cuando le convenga) completa su eliminación. No hace falta eliminar nada manualmente, salvo que se acabe de mostrar una lista de archivos restantes.
german.UninstalledMost=Die Deinstallation von Radiata ist abgeschlossen.%n%nWindows erledigt einen Teil der Bereinigung selbst – wurden die Controller-Treiber entfernt, schließt ein Neustart (jetzt oder später) ihre Entfernung ab. Es muss nichts von Hand entfernt werden, sofern nicht gerade eine Liste verbliebener Dateien angezeigt wurde.
japanese.UninstalledMost=Radiata のアンインストールが完了しました。%n%n残りのクリーンアップは Windows が自動的に行います。コントローラードライバーを削除した場合は、再起動（今すぐ、または都合のよいときに）で削除が完了します。残ったファイルの一覧が直前に表示されていなければ、手動で削除するものはありません。
arabic.UninstalledMost=اكتمل إلغاء تثبيت Radiata.%n%nسينهي Windows بعض التنظيف من تلقاء نفسه. إذا أزيلت برامج تشغيل وحدة التحكم، فإن إعادة التشغيل (الآن أو في الوقت المناسب لك) تكمل إزالتها. لا يلزم إزالة أي شيء يدويًا ما لم تعرض للتو قائمة بالملفات المتبقية.

[CustomMessages]
english.InstallDrivers=Install drivers (recommended)
spanish.InstallDrivers=Instalar los controladores (recomendado)
german.InstallDrivers=Treiber installieren (empfohlen)
japanese.InstallDrivers=ドライバーをインストール（推奨）
arabic.InstallDrivers=تثبيت برامج التشغيل (موصى به)
english.LaunchRadiata=Launch Radiata
spanish.LaunchRadiata=Iniciar Radiata
german.LaunchRadiata=Radiata starten
japanese.LaunchRadiata=Radiata を起動
arabic.LaunchRadiata=تشغيل Radiata
english.LeftoversIntro=These files remain in the Radiata folder. Review them before deciding whether to remove them:
spanish.LeftoversIntro=Estos archivos permanecen en la carpeta de Radiata. Revísalos antes de decidir si los eliminas:
german.LeftoversIntro=Diese Dateien bleiben im Radiata-Ordner. Prüfe sie, bevor du sie löschst:
japanese.LeftoversIntro=Radiata フォルダーに次のファイルが残っています。削除する前に内容を確認してください:
arabic.LeftoversIntro=تبقى هذه الملفات في مجلد Radiata. راجعها قبل أن تقرر إزالتها:
english.LeftoversMore=…and %1 more
spanish.LeftoversMore=…y %1 más
german.LeftoversMore=…und %1 weitere
japanese.LeftoversMore=…ほか %1 件
arabic.LeftoversMore=…و %1 أخرى
english.DriversTaskIntro=ViGEmBus and HidHide install Windows drivers that add controller handling and device visibility controls. They do not change controller firmware or modify game files. Removing these shared drivers can affect other controller tools.
spanish.DriversTaskIntro=ViGEmBus y HidHide instalan controladores de Windows que añaden gestión de mandos y controles de visibilidad de dispositivos. No cambian el firmware de los mandos ni modifican archivos de juegos. Quitar estos controladores compartidos puede afectar a otras herramientas de mandos.
german.DriversTaskIntro=ViGEmBus und HidHide installieren Windows-Treiber, die Controller-Verarbeitung und Gerätesichtbarkeitssteuerung hinzufügen. Sie ändern weder die Firmware von Controllern noch Spieldateien. Das Entfernen dieser gemeinsam genutzten Treiber kann andere Controller-Tools beeinträchtigen.
japanese.DriversTaskIntro=ViGEmBus と HidHide は、コントローラーの処理とデバイスの可視性の制御を追加する Windows ドライバーをインストールします。コントローラーのファームウェアは変更せず、ゲームファイルも変更しません。これらの共有ドライバーを削除すると、他のコントローラーツールに影響することがあります。
arabic.DriversTaskIntro=يثبت ViGEmBus وHidHide برامج تشغيل Windows تضيف معالجة وحدات التحكم وعناصر تحكم في ظهور الأجهزة. لا يغيران البرنامج الثابت لوحدات التحكم ولا يعدلان ملفات الألعاب. قد تؤثر إزالة برامج التشغيل المشتركة هذه في أدوات تحكم أخرى.

english.CleanupFailed=Radiata cleanup failed. Uninstall has stopped and application files were kept. Resolve the cleanup error and retry.
spanish.CleanupFailed=La limpieza de Radiata ha fallado. La desinstalación se ha detenido y se han conservado los archivos. Resuelve el error e inténtalo de nuevo.
german.CleanupFailed=Radiata konnte die Bereinigung nicht abschließen. Die Deinstallation wurde gestoppt und Programmdateien wurden behalten. Behebe den Fehler und versuche es erneut.
japanese.CleanupFailed=Radiata のクリーンアップに失敗しました。アンインストールを停止し、アプリのファイルを保持しました。エラーを解決して再試行してください。
arabic.CleanupFailed=فشل تنظيف Radiata. توقف إلغاء التثبيت واحتفظ بملفات التطبيق. عالج خطأ التنظيف ثم أعد المحاولة.

[Tasks]
; Fresh installs only (Check) — on an upgrade the drivers are already whatever the user chose,
; and a silent update must never pop UAC. ⚠ "Fresh" is not enough on its own: the in-app updater
; running on a portable (ZIP / dev) copy lands here with NO uninstall key, so IsUpgrade is false and
; the task would run, parking the "silent" update on a UAC prompt for --install-drivers. The updater
; always passes /RADIATARELAUNCH=1; that path never gets the task.
Name: "drivers"; Description: "{cm:InstallDrivers}"; Check: (not IsUpgrade) and (not RelaunchRequested)

[Files]
; The whole staged payload, recursively. ⚠ Dual-maintenance trap: a file added to the shipped
; payload must ALSO be added to App.OwnedFiles/OwnedDirs (the portable ZIP uninstaller's manifest)
; — see docs/INSTALLER.md and docs/BUILD-RELEASE.md.
Source: "{#PayloadDir}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{autoprograms}\Radiata"; Filename: "{app}\Radiata.exe"

[Registry]
; Start-with-Windows from the moment of install, so a user who abandons the wizard doesn't end up
; with an app that silently never comes back after a reboot. The value data matches what
; StartupManager.Format writes ("path in quotes" + the --autostart switch, value name "Radiata"), so
; the app's format check leaves it alone. This entry is also the ON switch the logon task reads at
; sign-in (docs/INSTALLER.md ▸ Autostart). ⚠ Fresh installs only (Check) — the installer runs on every
; silent update, and without the gate an update would resurrect autostart for a user who deliberately
; turned it off. OOBE's finish step and the Settings/tray checkboxes own the setting afterwards. No
; uninsdeletevalue on purpose: removal belongs to `--uninstall-cleanup` alone (docs/INSTALLER.md ▸
; Uninstall ownership split).
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; \
  ValueName: "Radiata"; ValueData: """{app}\Radiata.exe"" --autostart"; Check: not IsUpgrade

[Run]
; Start in the installing user's context. Radiata captures that SID before its own UAC relay,
; so alternate administrator credentials do not redirect the recovery task to another account.
Filename: "{app}\Radiata.exe"; Parameters: "--install-drivers"; Tasks: drivers; \
  Flags: shellexec waituntilterminated

; Interactive finish-page checkbox. skipifsilent keeps it out of silent updates.
Filename: "{app}\Radiata.exe"; Description: "{cm:LaunchRadiata}"; Flags: postinstall skipifsilent nowait

; Silent-update relaunch: the in-app updater passes /RADIATARELAUNCH=1 so the tray comes back
; after a /SILENT upgrade replaced the running instance. Never runs otherwise. --updated tells the
; relaunched instance it is the post-update process, so it can quiet the sentry card for the swap
; window (the update itself manufactures the Steam pre-cloak-handle state the card warns about).
Filename: "{app}\Radiata.exe"; Parameters: "--updated"; Flags: nowait; Check: RelaunchRequested

[UninstallDelete]
; Processed as the LAST step of uninstallation — after the log-based file pass — so this is a
; second, later delete attempt for Radiata.exe. Needed because the exe's image can still be held
; (AV scan / a just-terminated process's section) at the instant the first pass reaches it; a live
; uninstall run left exactly this one file behind. Deliberately NARROW: the Inno docs warn hard
; against filesandordirs on {app} (user-dropped files, wrong-directory installs).
Type: files; Name: "{app}\Radiata.exe"
Type: dirifempty; Name: "{app}"

; ⚠ There is deliberately NO [UninstallRun] section. The cleanup hook is Exec'd from [Code] at
; usUninstall instead (see CurUninstallStepChanged), because [UninstallRun] executes AFTER
; usUninstall — where TryDeleteRadiataExe had already deleted Radiata.exe whenever the app wasn't
; running, so the Exec failed with file-not-found (2) and the ENTIRE Windows-state cleanup silently
; skipped: no options dialog, orphaned Run key, drivers never offered. Seen live twice (0.14.878 and
; 0.14.1015, Aug 30 2026, /LOG-confirmed); it only ever worked when a running instance kept the exe
; locked past the early delete. Don't reintroduce an [UninstallRun] cleanup entry.

[Code]
// The OOBE chrome palette (App.xaml Ui*/HeadingInk), as VCL TColor ($00BBGGRR — byte order is
// REVERSED from the XAML hex). Keep in sync with App.xaml if the app is ever retoned.
const
  RadiataWindowBg  = $FCF8F5;  // UiWindowBg  #F5F8FC
  RadiataBodyInk   = $453B35;  // UiBodyInk   #353B45
  RadiataHeadingInk = $52443C; // HeadingInk  #3C4452
  RadiataMutedInk  = $9B8C83;  // UiMutedInk  #838C9B

// Recolour the stock wizard to the OOBE chrome theme. Only colours + the wizard bitmaps — the
// buttons stay native Windows controls on purpose (owner-drawing/skinning DLLs were rejected as a
// supply-chain risk for a cosmetic gain).
procedure ApplyRadiataTheme;
begin
  WizardForm.Color := RadiataWindowBg;
  WizardForm.InnerPage.Color := RadiataWindowBg;
  WizardForm.WelcomePage.Color := RadiataWindowBg;
  WizardForm.FinishedPage.Color := RadiataWindowBg;
  WizardForm.TasksList.Color := RadiataWindowBg;
  WizardForm.RunList.Color := RadiataWindowBg;
  WizardForm.ReadyMemo.Color := RadiataWindowBg;
  WizardForm.ReadyMemo.Font.Color := RadiataBodyInk;
  // The summary is a few lines at most — no scrollbars, no sunken border; flat like OOBE text.
  WizardForm.ReadyMemo.ScrollBars := ssNone;
  WizardForm.ReadyMemo.BorderStyle := bsNone;

  // Header strip on the same background, so the small wizard bitmap's field blends in seamlessly.
  WizardForm.MainPanel.Color := RadiataWindowBg;
  WizardForm.PageNameLabel.Font.Color := RadiataHeadingInk;
  WizardForm.PageDescriptionLabel.Font.Color := RadiataMutedInk;

  WizardForm.WelcomeLabel1.Font.Color := RadiataHeadingInk;
  WizardForm.WelcomeLabel2.Font.Color := RadiataBodyInk;
  WizardForm.FinishedHeadingLabel.Font.Color := RadiataHeadingInk;
  WizardForm.FinishedLabel.Font.Color := RadiataBodyInk;
  WizardForm.SelectTasksLabel.Font.Color := RadiataBodyInk;
  WizardForm.ReadyLabel.Font.Color := RadiataBodyInk;
  WizardForm.StatusLabel.Font.Color := RadiataBodyInk;
  WizardForm.FilenameLabel.Font.Color := RadiataMutedInk;
  // No watermark on the inner pages: every attempt gets covered or cropped by the
  // opaque notebook/list controls — the wheel lives on the Welcome/Finished banner only.
end;

// The tasks page carries the plain-language driver explanation as page text ABOVE the checkbox
// (a paragraph this long inside the checkbox label itself renders as one giant wrapped label).
// The label grows and the checklist shifts down by the same amount.
procedure InitializeWizard;
var
  delta: Integer;
begin
  ApplyRadiataTheme;
  // The drivers checkbox is THE decision on this page — render it at heading size.
  WizardForm.TasksList.Font.Size := 13;
  WizardForm.TasksList.MinItemHeight := ScaleY(34);
  WizardForm.SelectTasksLabel.AutoSize := False;
  WizardForm.SelectTasksLabel.WordWrap := True;
  WizardForm.SelectTasksLabel.Caption := CustomMessage('DriversTaskIntro');
  delta := ScaleY(28);
  WizardForm.SelectTasksLabel.Height := WizardForm.SelectTasksLabel.Height + delta;
  WizardForm.TasksList.Top := WizardForm.TasksList.Top + delta;
  WizardForm.TasksList.Height := WizardForm.TasksList.Height - delta;
end;

// Same theme for the uninstall progress window.
procedure InitializeUninstallProgressForm;
begin
  UninstallProgressForm.Color := RadiataWindowBg;
  UninstallProgressForm.InnerPage.Color := RadiataWindowBg;
  UninstallProgressForm.MainPanel.Color := clWhite;
  UninstallProgressForm.PageNameLabel.Font.Color := RadiataHeadingInk;
  UninstallProgressForm.PageDescriptionLabel.Font.Color := RadiataMutedInk;
  UninstallProgressForm.StatusLabel.Font.Color := RadiataBodyInk;
end;

function IsUpgrade: Boolean;
begin
  Result := RegKeyExists(HKEY_CURRENT_USER,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{FC9B183F-8F24-4343-82FC-7D8CE9914300}_is1');
end;

// ── Close a running Radiata before any file is replaced ─────────────────────────────────────────
// Restart Manager (CloseApplications) can start copying while the old process is still unloading, so
// its native teardown runs against replaced files. First ask the running tray to leave through its own
// ExitApp by signalling the named event it owns (a build without that event ignores this: OpenEventW
// fails), then wait until Radiata.exe and the ArcadeHost helper under {app} can be opened for write.
// RM stays the fallback. The event name is duplicated from App.xaml.cs (QuitEventName).
function OpenEventW(dwDesiredAccess: Cardinal; bInheritHandle: Integer; lpName: String): THandle;
  external 'OpenEventW@kernel32.dll stdcall';
function SetEvent(hEvent: THandle): Integer;
  external 'SetEvent@kernel32.dll stdcall';
function CloseHandle(hObject: THandle): Integer;
  external 'CloseHandle@kernel32.dll stdcall';
function CreateFileW(lpFileName: String; dwDesiredAccess, dwShareMode: Cardinal; lpSecurityAttributes: Cardinal;
  dwCreationDisposition, dwFlagsAndAttributes: Cardinal; hTemplateFile: THandle): THandle;
  external 'CreateFileW@kernel32.dll stdcall';

// True when the file exists and cannot be opened for write (a running image holds it).
function ImageInUse(const Path: String): Boolean;
var
  h: THandle;
begin
  Result := False;
  if not FileExists(Path) then Exit;
  h := CreateFileW(Path, $40000000 {GENERIC_WRITE}, 0, 0, 3 {OPEN_EXISTING}, $80 {NORMAL}, 0);
  if h = THandle(-1) then
    Result := True
  else
    CloseHandle(h);
end;

function RadiataRunning: Boolean;
begin
  Result := ImageInUse(ExpandConstant('{app}\Radiata.exe'))
    or ImageInUse(ExpandConstant('{app}\ArcadeHost\Radiata.ArcadeHost.exe'));
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ev: THandle;
  i: Integer;
begin
  Result := '';
  if not RadiataRunning then Exit;
  ev := OpenEventW($2 {EVENT_MODIFY_STATE}, 0, 'Local\Radiata.QuitRequest');
  if ev <> 0 then
  begin
    SetEvent(ev);
    CloseHandle(ev);
  end;
  // Bounded (~15 s): an unsaved-edits prompt or an older build that ignores the request falls through
  // to Restart Manager below.
  for i := 1 to 30 do
  begin
    if not RadiataRunning then Break;
    Sleep(500);
  end;
end;

function RelaunchRequested: Boolean;
begin
  Result := ExpandConstant('{param:RADIATARELAUNCH|0}') = '1';
end;

// Radiata.exe outlives the standard delete passes: the AV on-exit scan of the just-terminated
// 100 MB image (two of them — --uninstall-cleanup and its elevated child) holds its section for
// several seconds. A bounded timed retry (20 x 500 ms) waits that out. Silent; adds time only
// while the file resists.
procedure TryDeleteRadiataExe;
var
  i: Integer;
  exe: String;
begin
  exe := ExpandConstant('{app}\Radiata.exe');
  for i := 1 to 20 do
  begin
    if not FileExists(exe) then break;
    if DeleteFile(exe) then break;
    Sleep(500);
  end;
end;

// Everything under Dir except the uninstaller's own pair (Inno self-deletes those last).
procedure ListLeftovers(const Dir: String; var List: String; var Count: Integer);
var
  fr: TFindRec;
begin
  if FindFirst(Dir + '\*', fr) then
  begin
    try
      repeat
        if (fr.Name <> '.') and (fr.Name <> '..') then
        begin
          if (fr.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
            ListLeftovers(Dir + '\' + fr.Name, List, Count)
          else if (CompareText(fr.Name, 'unins000.exe') <> 0)
              and (CompareText(fr.Name, 'unins000.dat') <> 0) then
          begin
            Count := Count + 1;
            if Count <= 10 then
              List := List + #13#10 + Dir + '\' + fr.Name;
          end;
        end;
      until not FindNext(fr);
    finally
      FindClose(fr);
    end;
  end;
end;

// usUninstall fires BEFORE the log-based file pass, so clearing the locked exe here keeps that
// pass from ever failing — Inno's "some elements could not be removed" flag latches on the first
// failed delete and never clears, so the only way to avoid the scary partial-success message is
// to make the early passes succeed. usPostUninstall is the backstop: retry once more, drop the
// now-empty dir, and if anything genuinely remains, name it. Inno's own closing message can't be
// suppressed from [Code]; its text is corrected in [Messages] ▸ UninstalledMost.
// ⚠ No driver line from this script. The cleanup hook reports the drivers per driver (removed /
// pending restart / left in place as another program's / could not be removed) in its own dialog,
// and a second line here can only agree with it or contradict it — a DeleteFlag probe once told a
// user "the drivers are uninstalled" right after the hook said ViGEmBus could not be removed.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  list, appDir: String;
  count, rc: Integer;
  params: String;
begin
  if CurUninstallStep = usUninstall then
  begin
    // Windows/controller state is the APP's to clean (Run key, HidHide allow-list + cloak, recovery
    // task, opt-in driver/settings removal); files are the uninstaller's. This Exec MUST come before
    // TryDeleteRadiataExe — it runs the exe it would delete — and it lives here rather than in
    // [UninstallRun] because that section executes after usUninstall (see the section-level note).
    // Abort is supported from usUninstall, before the log-based file pass. A failed cleanup keeps
    // the executable and recovery implementation available for a retry.
    // /SILENT or /VERYSILENT: the cleanup must not raise its WPF options prompt (nobody is watching a
    // scripted removal) - it runs with no opt-ins instead. The interactive default is unchanged.
    if UninstallSilent then params := '--uninstall-cleanup --silent'
    else params := '--uninstall-cleanup';
    if not Exec(ExpandConstant('{app}\Radiata.exe'), params, '',
                SW_SHOWNORMAL, ewWaitUntilTerminated, rc) then
    begin
      Log('Radiata cleanup hook could not be started (' + SysErrorMessage(DLLGetLastError) + ')');
      if not UninstallSilent then
        MsgBox(CustomMessage('CleanupFailed'), mbError, MB_OK);
      Abort;
    end;
    Log('Radiata cleanup hook exit code ' + IntToStr(rc));
    if rc <> 0 then
    begin
      if not UninstallSilent then
        MsgBox(CustomMessage('CleanupFailed'), mbError, MB_OK);
      Abort;
    end;
    TryDeleteRadiataExe;
  end;
  if CurUninstallStep = usPostUninstall then
  begin
    appDir := ExpandConstant('{app}');
    TryDeleteRadiataExe;
    RemoveDir(appDir);
    if DirExists(appDir) then
    begin
      list := '';
      count := 0;
      ListLeftovers(appDir, list, count);
      if count > 0 then
      begin
        if count > 10 then
          list := list + #13#10 + FmtMessage(CustomMessage('LeftoversMore'), [IntToStr(count - 10)]);
        SuppressibleMsgBox(CustomMessage('LeftoversIntro') + #13#10 + list, mbInformation, MB_OK, IDOK);
      end;
    end;
  end;
end;
